//go:build prequant

package chatapp

import (
	_ "embed"
	"fmt"
	"time"

	"github.com/townsendmerino/goinfer/decoder"
	"github.com/townsendmerino/goinfer/internal/giw"
	"github.com/townsendmerino/goinfer/tokenizer"
)

// modelGIW is the prequant bundle baked into the binary: serialized int8
// weights + a metadata-only GGUF for the tokenizer (see cmd/prequant). A BUILD
// INPUT generated by build-embed.sh --prequant (gitignored, not committed).
//
//go:embed model.giw
var modelGIW []byte

// hasEmbeddedModel reports that this build has a baked-in model.
const hasEmbeddedModel = true

// loadEmbedded maps the prequant bundle: the int8 weight arrays are ALIASED
// straight out of modelGIW (the binary's image — no dequant, no requant, no
// heap copy), and the tokenizer loads from the bundle's metadata GGUF. This is
// the fast / low-RAM path; modelGIW is a package global, so the aliased weights
// stay valid for the process lifetime. --model-tmp does not apply (nothing is
// written to disk).
//
// On a bundle mismatch (version/quant/CRC — e.g. a stale build) it returns the
// error so main can report it; the user can fall back with --model <gguf>.
func loadEmbedded(_ bool, opts decoder.Options) (*session, error) {
	t0 := time.Now()
	weightsBlob, tokGGUF, err := giw.Read(modelGIW)
	if err != nil {
		return nil, fmt.Errorf("prequant bundle: %w (rebuild it, or run with --model <gguf>)", err)
	}
	progress("mapping weights…")
	w, err := decoder.LoadSerializedWeights(weightsBlob)
	if err != nil {
		return nil, fmt.Errorf("prequant weights: %w (rebuild the bundle, or run with --model <gguf>)", err)
	}
	tk, err := tokenizer.LoadGGUFBytes(tokGGUF)
	if err != nil {
		return nil, fmt.Errorf("prequant tokenizer: %w", err)
	}
	model, err := decoder.NewModel(w, opts.Backend)
	if err != nil {
		return nil, err
	}
	return newSession(tk, model, opts, time.Since(t0)), nil
}
