//go:build prequant

package chatapp

import (
	_ "embed"
	"fmt"
	"time"

	"github.com/townsendmerino/goinfer/decoder"
	"github.com/townsendmerino/goinfer/internal/giw"
	"github.com/townsendmerino/goinfer/tokenizer"
)

// modelGIW is the prequant bundle baked into the binary: serialized int8
// weights + a metadata-only GGUF for the tokenizer (see cmd/prequant). A BUILD
// INPUT generated by build-embed.sh --prequant (gitignored, not committed).
//
//go:embed model.giw
var modelGIW []byte

// hasEmbeddedModel reports that this build has a baked-in model.
const hasEmbeddedModel = true

// loadEmbedded maps the prequant bundle: the int8 weight arrays are ALIASED
// straight out of modelGIW (the binary's image — no dequant, no requant, no
// heap copy), and the tokenizer loads from the bundle's metadata GGUF. This is
// the fast / low-RAM path; modelGIW is a package global, so the aliased weights
// stay valid for the process lifetime. --model-tmp does not apply (nothing is
// written to disk).
//
// On a bundle mismatch (version/quant/CRC — e.g. a stale build) it returns the
// error so main can report it; the user can fall back with --model <gguf>.
func loadEmbedded(_ bool, opts decoder.Options) (*session, error) {
	t0 := time.Now()
	weightsBlob, tokGGUF, err := giw.Read(modelGIW)
	if err != nil {
		return nil, fmt.Errorf("prequant bundle: %w (rebuild it, or run with --model <gguf>)", err)
	}
	progress("mapping weights…")
	w, err := decoder.LoadSerializedWeights(weightsBlob)
	if err != nil {
		return nil, fmt.Errorf("prequant weights: %w (rebuild the bundle, or run with --model <gguf>)", err)
	}
	// N-25: a .giw's tok half is GGUF metadata for a GGUF-sourced bundle and RAW tokenizer.json
	// for a safetensors-sourced one. This path tried only the GGUF form, so an embedded build
	// made from a safetensors checkpoint produced a binary that exited at startup — the same
	// fallback loadFromPath has always had, missing from the baked-in twin.
	tk, gerr := tokenizer.LoadGGUFBytes(tokGGUF)
	if gerr != nil {
		var jerr error
		if tk, jerr = tokenizer.LoadJSONBytes(tokGGUF); jerr != nil {
			// BOTH errors, not just the last: with only the JSON one, a corrupt GGUF-sourced
			// bundle reports "invalid JSON" and sends the reader down the wrong path.
			return nil, fmt.Errorf("prequant tokenizer: not a GGUF (%v) and not tokenizer.json (%v)", gerr, jerr)
		}
	}
	model, err := decoder.NewModel(w, opts.Backend)
	if err != nil {
		return nil, err
	}
	return newSession(tk, model, opts, time.Since(t0)), nil
}
