//go:build prequant

package chatapp

import (
	_ "embed"
	"fmt"
	"time"

	"github.com/townsendmerino/goinfer/decoder"
	"github.com/townsendmerino/goinfer/internal/giw"
	"github.com/townsendmerino/goinfer/internal/modelload"
)

// modelGIW is the prequant bundle baked into the binary: serialized int8
// weights + a metadata-only GGUF for the tokenizer (see cmd/prequant). A BUILD
// INPUT generated by build-embed.sh --prequant (gitignored, not committed).
//
//go:embed model.giw
var modelGIW []byte

// hasEmbeddedModel reports that this build has a baked-in model.
const hasEmbeddedModel = true

// quantIsFixedAtBuildTime is true here: loadEmbedded below never reads opts.Quant — the bundle's
// weights are already quantized at whatever cmd/prequant used when build-embed.sh baked
// internal/chatapp/model.giw (R6, docs/measurements/cold-user-2026-09-06-nobara-pc.md).
const quantIsFixedAtBuildTime = true

// loadEmbedded maps the prequant bundle: the int8 weight arrays are ALIASED
// straight out of modelGIW (the binary's image — no dequant, no requant, no
// heap copy), and the tokenizer loads from the bundle's metadata GGUF. This is
// the fast / low-RAM path; modelGIW is a package global, so the aliased weights
// stay valid for the process lifetime. --model-tmp does not apply (nothing is
// written to disk).
//
// On a bundle mismatch (version/quant/CRC — e.g. a stale build) it returns the
// error so main can report it; the user can fall back with --model <gguf>.
func loadEmbedded(_ bool, opts decoder.Options) (*session, error) {
	// N-78 (docs/audit-2026-09-10.md): decoder.NewModel below (unlike decoder.Load, which
	// loadFromPath uses) takes no *decoder.Options at all — there is no chokepoint downstream of
	// this function that could ever apply opts.LoRA to an already-serialized .giw bundle. Silently
	// dropping it made --lora on a prequant build a no-op that looked like a merged adapter.
	if opts.LoRA != "" {
		return nil, fmt.Errorf("--lora is not supported on a prequant build: the bundle's weights are pre-quantized and aliased from the binary image, with no base to merge an adapter into (rebuild with a safetensors base via --model, or use a non-prequant build)")
	}
	t0 := time.Now()
	weightsBlob, tokGGUF, err := giw.Read(modelGIW)
	if err != nil {
		return nil, fmt.Errorf("prequant bundle: %w (rebuild it, or run with --model <gguf>)", err)
	}
	progress("mapping weights…")
	w, err := decoder.LoadSerializedWeights(weightsBlob)
	if err != nil {
		return nil, fmt.Errorf("prequant weights: %w (rebuild the bundle, or run with --model <gguf>)", err)
	}
	// N-25: a .giw's tok half is GGUF metadata for a GGUF-sourced bundle and RAW tokenizer.json
	// for a safetensors-sourced one. This path tried only the GGUF form, so an embedded build
	// made from a safetensors checkpoint produced a binary that exited at startup — the same
	// fallback loadFromPath has always had, missing from the baked-in twin.
	tk, err := modelload.TokenizerFromTok(tokGGUF) // GGUF or raw tokenizer.json; both errors on failure
	if err != nil {
		return nil, fmt.Errorf("prequant tokenizer: %w", err)
	}
	model, err := decoder.NewModel(w, opts.Backend)
	if err != nil {
		return nil, err
	}
	return newSession(tk, model, opts, time.Since(t0)), nil
}
