package chat

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// The harmony (gpt-oss) renderer, pinned against HuggingFace's own template.
//
// The expected string below is NOT hand-written. It is what
// `tokenizer.apply_chat_template(..., chat_template=<the 16.7 KB template from the MXFP4 GGUF>)`
// produced, and goinfer's render was verified to encode to the SAME 78 token ids against the
// real gpt-oss vocab. Byte equality here plus that id check is what makes the renderer
// trustworthy; a hand-written expectation would only test that the code does what was typed.
//
// The clock is pinned because harmony's system preamble carries a LIVE date (strftime_now
// upstream), so an unpinned test would pass only on the day it was written.
func TestHarmony_byteExact(t *testing.T) {
	defer func() { timeNow = time.Now }()
	timeNow = func() time.Time { return time.Date(2026, 8, 16, 12, 0, 0, 0, time.UTC) }

	const want = "<|start|>system<|message|>You are ChatGPT, a large language model trained by OpenAI.\n" +
		"Knowledge cutoff: 2024-06\n" +
		"Current date: 2026-08-16\n\n" +
		"Reasoning: medium\n\n" +
		"# Valid channels: analysis, commentary, final. Channel must be included for every message." +
		"<|end|><|start|>user<|message|>Write a Python function that returns the nth Fibonacci number." +
		"<|end|><|start|>assistant"

	got := Harmony().Render("", []Turn{
		{Role: "user", Content: "Write a Python function that returns the nth Fibonacci number."},
	})
	if got != want {
		t.Errorf("harmony render differs from HuggingFace's\n got: %q\nwant: %q", got, want)
	}
}

// TestHarmony_stopsAreUpstreams pins the turn stops to gpt-oss's own generation_config.json
// (eos_token_id [200002, 199999, 200012] — <|return|>, <|endoftext|>, <|call|>), and asserts <|end|>
// is NOT among them. <|end|> closes a message, not a turn: with it as a stop, a gpt-oss reply ended
// after its analysis channel and never reached the final answer.
func TestHarmony_stopsAreUpstreams(t *testing.T) {
	got := map[string]bool{}
	for _, s := range Harmony().Stops().Strings {
		got[s] = true
	}
	for _, want := range []string{"<|return|>", "<|call|>", "<|endoftext|>"} {
		if !got[want] {
			t.Errorf("harmony stops %v lack %s, which gpt-oss's generation_config.json lists as a stop", Harmony().Stops().Strings, want)
		}
	}
	if got["<|end|>"] {
		t.Errorf("harmony stops include <|end|>: that ends a MESSAGE, so every reply would stop after its " +
			"analysis channel, before the final answer")
	}
	if len(got) != 3 {
		t.Errorf("harmony stops = %v, want exactly upstream's three", Harmony().Stops().Strings)
	}
}

// Detect must resolve harmony, and must NOT confuse it with Gemma 4. The two are one
// character apart in the marker Detect keys on: Gemma tests "<|channel>", harmony's is
// "<|channel|>", and "<|channel|>" does NOT contain "<|channel>" because the trailing pipe
// breaks the substring. That near-miss is why the ordering is asserted rather than assumed —
// a Detect that returned Gemma4() here would render gpt-oss through turn markers and produce
// a plausible, wrong prompt rather than an error.
func TestDetect_harmonyNotGemma4(t *testing.T) {
	// bare checkpoint (no chat_template) — the vocab-marker route, which is what the real
	// gpt-oss HF checkpoint hits, since it ships no template at all.
	harmonyVocab := map[string]bool{"<|start|>": true, "<|message|>": true, "<|channel|>": true, "<|end|>": true}
	got, err := Detect(Meta{HasToken: func(s string) bool { return harmonyVocab[s] }})
	if err != nil {
		t.Fatalf("Detect(bare gpt-oss vocab): %v", err)
	}
	if got.Name() != "harmony" {
		t.Errorf("bare gpt-oss vocab resolved to %q, want harmony", got.Name())
	}

	// Gemma 4 must still win on its own markers, which is the regression this ordering risks.
	g4, err := Detect(Meta{ChatTemplate: "…{{ '<|turn>' }}…{{ '<|channel>thought' }}…"})
	if err != nil {
		t.Fatalf("Detect(gemma4 template): %v", err)
	}
	if g4.Name() != "gemma4" {
		t.Errorf("gemma4 template resolved to %q — harmony's branch stole it", g4.Name())
	}
}

// TestHarmony_conversationMatchesHF pins the conversation rendering to gpt-oss's own chat template (testdata/chat_think_goldens/
// harmony_history.json, generated by scripts/pin_harmony_history.py from the template inside the MXFP4 GGUF). TestHarmony_byteExact
// above covers one user turn; this covers what that test could not see — a system prompt, and above all an assistant turn earlier in
// the conversation, which the template renders on the `final` channel (without a channel the history is in a shape the model was not
// trained on, while the preamble tells it "Channel must be included for every message"). The prior turn's reasoning is dropped
// however it was supplied, which a case here pins as well.
func TestHarmony_conversationMatchesHF(t *testing.T) {
	defer func() { timeNow = time.Now }()
	timeNow = func() time.Time { return time.Date(2026, 8, 16, 12, 0, 0, 0, time.UTC) }

	raw, err := os.ReadFile(filepath.Join("..", "testdata", "chat_think_goldens", "harmony_history.json"))
	if err != nil {
		t.Fatal(err)
	}
	var g struct {
		Cases []struct {
			Name     string `json:"name"`
			Messages []struct {
				Role     string `json:"role"`
				Content  string `json:"content"`
				Thinking string `json:"thinking"`
			} `json:"messages"`
			Kwargs map[string]string `json:"kwargs"`
			Prompt string            `json:"prompt"`
		} `json:"cases"`
	}
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatal(err)
	}
	if len(g.Cases) < 10 {
		t.Fatalf("only %d golden cases", len(g.Cases))
	}
	for _, c := range g.Cases {
		system, turns := "", []Turn(nil)
		for _, m := range c.Messages {
			if m.Role == "system" {
				system = m.Content
				continue
			}
			turns = append(turns, Turn{Role: m.Role, Content: m.Content, Reasoning: m.Thinking})
		}
		tm := Harmony()
		if e, ok := c.Kwargs["reasoning_effort"]; ok {
			tm = tm.WithReasoningEffort(e)
		}
		got := strings.Replace(tm.Render(system, turns), "Current date: 2026-08-16", "Current date: {DATE}", 1)
		if got != c.Prompt {
			t.Errorf("%s:\n got  %q\n want %q", c.Name, got[len(got)-min(len(got), 260):], c.Prompt[len(c.Prompt)-min(len(c.Prompt), 260):])
		}
	}
}

// WithReasoningEffort acts on gpt-oss's template and on nothing else, and only for the three values its template takes — so a client
// that sends a bare reasoning_effort to every endpoint (dsh does) moves no other model's prompt, and a value gpt-oss does not know
// is ignored rather than written into the system block.
func TestWithReasoningEffort(t *testing.T) {
	defer func() { timeNow = time.Now }()
	timeNow = func() time.Time { return time.Date(2026, 8, 16, 12, 0, 0, 0, time.UTC) }

	turns := []Turn{{Role: "user", Content: "Hi"}}
	base := Harmony().Render("", turns)
	if !strings.Contains(base, "Reasoning: medium\n\n") {
		t.Fatal("setup: the default effort is medium")
	}
	for in, want := range map[string]string{"low": "low", "HIGH": "high", " Medium ": "medium"} {
		got := Harmony().WithReasoningEffort(in).Render("", turns)
		if got != strings.Replace(base, "Reasoning: medium", "Reasoning: "+want, 1) {
			t.Errorf("effort %q: rendered %q", in, got)
		}
	}
	for _, in := range []string{"", "none", "minimal", "xhigh", "ultra", "low\n\n# injected"} {
		if got := Harmony().WithReasoningEffort(in); got.Render("", turns) != base {
			t.Errorf("effort %q must be ignored, but the prompt changed", in)
		}
	}
	// Every other family, and the nil template, are returned as they are.
	for _, tm := range []*Template{ChatML(), Gemma4(), Llama3(), nil} {
		if tm.WithReasoningEffort("high") != tm {
			t.Errorf("%v: WithReasoningEffort must be a no-op for a template with no such knob", nameOf(tm))
		}
	}
	if e, ok := NormalizeReasoningEffort("Low "); !ok || e != "low" {
		t.Errorf("NormalizeReasoningEffort(\"Low \") = %q, %v", e, ok)
	}
}

func nameOf(t *Template) string {
	if t == nil {
		return "nil"
	}
	return t.Name()
}
