//go:build embed

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"os"

	"github.com/klauspost/compress/zstd"
)

// modelZst is the GGUF model, zstd-compressed, baked into the binary. The file
// is a BUILD INPUT generated by build-embed.sh (it is gitignored, not committed
// — at ~430 MB it exceeds GitHub's 100 MB file cap). Without -tags embed this
// file is not compiled, so the default build carries neither the model nor the
// zstd dependency.
//
//go:embed model.gguf.zst
var modelZst []byte

// materializeEmbedded inflates the baked-in model to a temp .gguf and returns
// its path (decoder.Load mmaps a file). cleanup removes the temp file; call it
// on exit. The plan's accepted cost: a second or two of cold start + the
// inflated model briefly on disk.
func materializeEmbedded() (path string, cleanup func(), ok bool) {
	f, err := os.CreateTemp("", "goinfer-model-*.gguf")
	if err != nil {
		fatal("embed: create temp file: %v", err)
	}
	dec, err := zstd.NewReader(bytes.NewReader(modelZst))
	if err != nil {
		fatal("embed: open zstd reader: %v", err)
	}
	defer dec.Close()
	if _, err := io.Copy(f, dec); err != nil {
		f.Close()
		os.Remove(f.Name())
		fatal("embed: inflate model: %v", err)
	}
	if err := f.Close(); err != nil {
		os.Remove(f.Name())
		fatal("embed: close temp model: %v", err)
	}
	return f.Name(), func() { os.Remove(f.Name()) }, true
}

func fatal(format string, a ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", a...)
	os.Exit(1)
}
