//go:build embed

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"os"

	"github.com/klauspost/compress/zstd"
)

// modelZst is the GGUF model, zstd-compressed, baked into the binary. The file
// is a BUILD INPUT generated by build-embed.sh (it is gitignored, not committed
// — at ~430 MB it exceeds GitHub's 100 MB file cap). Without -tags embed this
// file is not compiled, so the default build carries neither the model nor the
// zstd dependency.
//
//go:embed model.gguf.zst
var modelZst []byte

// hasEmbeddedModel reports that this build has a baked-in model.
const hasEmbeddedModel = true

// embeddedModelBytes inflates the baked-in model fully into memory. This is the
// default path: the returned GGUF bytes are loaded with no filesystem access,
// so the binary runs on a read-only / FROM-scratch filesystem.
func embeddedModelBytes() ([]byte, error) {
	dec, err := zstd.NewReader(bytes.NewReader(modelZst))
	if err != nil {
		return nil, fmt.Errorf("embed: open zstd reader: %w", err)
	}
	defer dec.Close()
	// Preallocate generously (compressed ≈ uncompressed for high-entropy int4
	// weights) to avoid repeated buffer doubling on the way up to ~470 MB.
	buf := bytes.NewBuffer(make([]byte, 0, len(modelZst)+len(modelZst)/4))
	if _, err := io.Copy(buf, dec); err != nil {
		return nil, fmt.Errorf("embed: inflate model: %w", err)
	}
	return buf.Bytes(), nil
}

// embeddedModelTemp stream-inflates the baked-in model to a temp .gguf and
// returns its path (the --model-tmp / GOINFER_MODEL_TMP opt-out). Peak RAM is
// lower than embeddedModelBytes — the inflated model lands on disk and is paged
// in on demand during the load rather than held on the heap — at the cost of
// needing a writable temp dir. cleanup removes the file; call it once the model
// is built (the weights are fresh copies, so the file isn't needed after load).
func embeddedModelTemp() (path string, cleanup func(), err error) {
	f, err := os.CreateTemp("", "goinfer-model-*.gguf")
	if err != nil {
		return "", nil, fmt.Errorf("embed: create temp file: %w", err)
	}
	dec, err := zstd.NewReader(bytes.NewReader(modelZst))
	if err != nil {
		f.Close()
		os.Remove(f.Name())
		return "", nil, fmt.Errorf("embed: open zstd reader: %w", err)
	}
	defer dec.Close()
	if _, err := io.Copy(f, dec); err != nil { // streams to disk, not the heap
		f.Close()
		os.Remove(f.Name())
		return "", nil, fmt.Errorf("embed: inflate model: %w", err)
	}
	if err := f.Close(); err != nil {
		os.Remove(f.Name())
		return "", nil, fmt.Errorf("embed: close temp model: %w", err)
	}
	return f.Name(), func() { os.Remove(f.Name()) }, nil
}
