package decoder

import (
	"fmt"
	"math"

	"github.com/townsendmerino/aikit/embed"
)

// FP8 E4M3 (OCP "e4m3fn": finite, no infinities) — the weight dtype of DeepSeek V3/V4 and
// Qwen3-FP8 safetensors checkpoints, where it appears as dtype "F8_E4M3".
//
// One byte per weight: 1 sign, 4 exponent (bias 7), 3 mantissa. Two departures from IEEE
// binary8-ish intuition, and both are the kind of detail that produces plausible-but-wrong
// numbers rather than an error:
//
//   - THERE ARE NO INFINITIES. The exponent-all-ones pattern is a normal number, so the
//     largest finite value is 448 (0x7E), not 240 or 240-ish as a "reserve inf" reading
//     would give. Only S.1111.111 (0x7F / 0xFF) is NaN.
//   - Subnormals are 2^-6 * m/8, i.e. the smallest positive is 2^-9 = 0.001953125 (0x01).
//
// The decode below is DERIVED from that spec rather than transcribed, and fp8_test.go gates
// all 256 byte patterns against a table generated by PyTorch's own float8_e4m3fn. That is the
// standard mxfp4.go set for the same class of problem ("NOT inferred — transcribed from the
// reference and verified bit-for-bit"): a wrong dequant table yields finite, plausibly-scaled,
// completely wrong weights, and nothing downstream errors.
//
// SCALES ARE NOT HERE, deliberately. These checkpoints are BLOCK-quantized: the scales live in
// a separate `<weight>.weight_scale_inv` tensor covering 2-D blocks of the weight (128x128 for
// both DeepSeek and Qwen3-FP8), so a lone fp8 tensor cannot be turned into floats. Composing
// the two is the loader's job — see fp8DequantBlocked.
const (
	fp8E4M3Bias     = 7
	fp8E4M3MantBits = 3
)

// fp8E4M3ToF32 decodes one e4m3fn byte. NaN maps to NaN; there are no infinities.
func fp8E4M3ToF32(b byte) float32 {
	sign := float64(1)
	if b&0x80 != 0 {
		sign = -1
	}
	exp := int((b >> fp8E4M3MantBits) & 0x0F)
	mant := int(b & 0x07)
	switch {
	case exp == 0x0F && mant == 0x07:
		return float32(math.NaN()) // the ONLY NaN pattern; every other all-ones exponent is finite
	case exp == 0:
		// Subnormal: no implicit leading 1, fixed exponent 2^(1-bias).
		return float32(sign * math.Ldexp(float64(mant)/8, 1-fp8E4M3Bias))
	default:
		return float32(sign * math.Ldexp(1+float64(mant)/8, exp-fp8E4M3Bias))
	}
}

// fp8E4M3Table is the decode as a 256-entry lookup, built once. The inner loop of a loader
// wants a table, not a branch per weight; the branchy form above stays as the derivation the
// test checks, so the table cannot drift from the spec without the test noticing.
var fp8E4M3Table = func() [256]float32 {
	var t [256]float32
	for i := range t {
		t[i] = fp8E4M3ToF32(byte(i))
	}
	return t
}()

// fp8DequantBlocked expands a block-quantized fp8 weight matrix into f32.
//
// w is the row-major [rows, cols] fp8 payload. scales is the row-major
// [ceil(rows/blockR), ceil(cols/blockC)] scale grid — ONE scale per 2-D block, already widened
// from whatever dtype it was stored in (BF16 for Qwen3-FP8, F32 for DeepSeek). Element (r, c)
// is w[r][c] * scales[r/blockR][c/blockC].
//
// The name upstream is `weight_scale_inv`, which reads like a reciprocal and is NOT one: HF's
// loaders MULTIPLY by it. Checked against the reference dequant rather than assumed — inverting
// it would produce a smooth, entirely wrong model.
func fp8DequantBlocked(w []byte, scales []float32, rows, cols, blockR, blockC int) ([]float32, error) {
	if blockR <= 0 || blockC <= 0 {
		return nil, fmt.Errorf("decoder(fp8): block size %dx%d must be positive", blockR, blockC)
	}
	if len(w) != rows*cols {
		return nil, fmt.Errorf("decoder(fp8): %d payload bytes for a [%d,%d] tensor (want %d)", len(w), rows, cols, rows*cols)
	}
	sR, sC := (rows+blockR-1)/blockR, (cols+blockC-1)/blockC
	if len(scales) != sR*sC {
		return nil, fmt.Errorf("decoder(fp8): %d scales for a [%d,%d] tensor at %dx%d blocks (want %d = %dx%d)",
			len(scales), rows, cols, blockR, blockC, sR*sC, sR, sC)
	}
	out := make([]float32, rows*cols)
	for r := range rows {
		srow := (r / blockR) * sC
		wrow, orow := r*cols, r*cols
		for c := range cols {
			out[orow+c] = fp8E4M3Table[w[wrow+c]] * scales[srow+c/blockC]
		}
	}
	return out, nil
}

// fp8Reconstruct reads one block-quantized fp8 linear from a safetensors checkpoint and
// returns it as a [out, in] row-major f32 matrix — the same shape and orientation
// gptqReconstruct/awqReconstruct return, so loadProj can treat all three alike.
//
// name is the full tensor name (".weight"); the scales sit beside it at ".weight_scale_inv".
// Both are read through aikit's byte/typed accessors: the payload is F8_E4M3 (byte-wide, so
// Uint8s), the scales are BF16 or F32 (so TensorF32 widens them).
//
// NO TRANSPOSE HAPPENS HERE. HF stores nn.Linear weights as [out, in] already, and fp8 does
// not repack them — unlike GPTQ/AWQ, whose packed layout is [in, out] and whose reconstructors
// therefore transpose. Adding a transpose here "for symmetry" would produce a clean, entirely
// wrong model.
func fp8Reconstruct(st *embed.SafetensorsFile, name string, in, out, blockR, blockC int) ([]float32, error) {
	wT, err := st.Tensor(name)
	if err != nil {
		return nil, fmt.Errorf("fp8 %q: %w", name, err)
	}
	if wT.DType != "F8_E4M3" {
		return nil, fmt.Errorf("fp8 %q: dtype %s, want F8_E4M3", name, wT.DType)
	}
	raw, err := wT.Uint8s()
	if err != nil {
		return nil, fmt.Errorf("fp8 %q payload: %w", name, err)
	}
	// Shape is checked against the ARCHITECTURE (in/out from the config), not just against
	// the scale grid: a weight/scale pair can be self-consistent and still be the wrong
	// tensor, which is the check gptoss_safetensors.go's own comment insists on.
	//
	// N-06: this comment was true of the INTENT and false of the code, which compared only the
	// element COUNT. out*in == in*out, so a [in,out]-shaped tensor passed and then loaded
	// transposed — every weight present, every one in the wrong place. The declared shape is
	// what distinguishes them, so compare that.
	if len(wT.Shape) != 2 || wT.Shape[0] != out || wT.Shape[1] != in {
		return nil, fmt.Errorf("fp8 %q: shape %v, arch expects [%d,%d] — a transposed tensor has "+
			"the same element count and would load silently", name, wT.Shape, out, in)
	}
	if len(raw) != out*in {
		return nil, fmt.Errorf("fp8 %q: %d payload bytes for [%d,%d]", name, len(raw), out, in)
	}
	sName := name + "_scale_inv"
	sR, sC := (out+blockR-1)/blockR, (in+blockC-1)/blockC
	scales, err := st.TensorF32(sName, sR, sC)
	if err != nil {
		return nil, fmt.Errorf("fp8 %q scales: %w", sName, err)
	}
	return fp8DequantBlocked(raw, scales, out, in, blockR, blockC)
}
