package decoder

// Generated model × hardware matrix (docs/completed/task-hardware-matrix.md).
//
// Mirrors capability_matrix_test.go's registry walk, but the columns are one thing: does each
// backend run each family on its RESIDENT (GPU) decode path? The cells are 100% derived from
// decoder.ResidentEligible (arch flags + the shared feature taxonomy) — the SAME predicate the
// runtime admits on — so the published "on what hardware" table can never silently drift from
// behavior. Model-free (no weights), so it runs in CI: a backend-feature change either updates
// docs/hardware-matrix.md or turns the build red (TestHardwareMatrix_fresh).
//
// Run `go test ./decoder -run HardwareMatrix -update` to regenerate; the plain run is the gate.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
)

const hwMatrixPath = "../docs/hardware-matrix.md"
const hwMatrixHeader = "<!-- GENERATED by go test ./decoder -run HardwareMatrix -update — DO NOT EDIT -->"

// residentBackends are the GPU columns, in display order. cpu is implicit (always ✅).
var residentBackends = []string{"webgpu", "cuda", "metal"}

// hwRow is one model family's resident eligibility per backend, keyed by the resolved
// Architecture.Name (aliases that share an adapter collapse to one row).
type hwRow struct {
	Display string
	Res     map[string]bool // backend → ResidentEligible
}

func buildHardwareRows(t *testing.T) ([]hwRow, error) {
	t.Helper()
	// G-03: the hardware rows depend on decodeRunnerEligible(), which reads these residency
	// env vars. Neutralize them so the matrix reflects the code, not the ambient environment.
	t.Setenv("GOINFER_GEMMA4_RESIDENT", "")
	t.Setenv("GOINFER_SSM_RESIDENT", "")
	keys := make([]string, 0, len(registry))
	for k := range registry {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	rows := map[string]*hwRow{}
	for _, mt := range keys {
		cfg := representativeConfig(mt)
		if cfg == nil {
			return nil, fmt.Errorf("model_type %q has no representativeConfig", mt)
		}
		doc, ok := familyDocs[mt]
		if !ok {
			return nil, fmt.Errorf("model_type %q has no familyDoc", mt)
		}
		arch, _, err := resolveArchitecture(cfg)
		if err != nil {
			return nil, fmt.Errorf("model_type %q failed to resolve: %w", mt, err)
		}
		if _, exists := rows[arch.Name]; exists {
			continue
		}
		res := map[string]bool{}
		for _, be := range residentBackends {
			res[be] = ResidentEligible(arch, be)
		}
		rows[arch.Name] = &hwRow{Display: doc.DisplayName, Res: res}
	}

	out := make([]hwRow, 0, len(rows))
	for _, r := range rows {
		out = append(out, *r)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Display < out[j].Display })
	return out, nil
}

func hwCell(resident bool) string {
	if resident {
		return "✅ resident"
	}
	return "CPU"
}

func renderHardwareMD(rows []hwRow, verified string) []byte {
	var b strings.Builder
	b.WriteString(hwMatrixHeader + "\n\n")
	b.WriteString("# goinfer model × hardware matrix\n\n")
	b.WriteString("Every family runs on the pure-Go CPU path; the GPU columns show resident\n")
	b.WriteString("acceleration with automatic, correctness-guaranteed CPU fallback (a backend that\n")
	b.WriteString("does not implement a family's features DECLINES to the staged/CPU path rather than\n")
	b.WriteString("running it silently wrong). Generated from `decoder.ResidentEligible` — arch flags\n")
	b.WriteString("plus the shared feature taxonomy, the single source of truth the runtime admits on.\n")
	b.WriteString("Regenerate with `go test ./decoder -run HardwareMatrix -update`.\n\n")

	b.WriteString("| Family | CPU | WebGPU | CUDA | Metal |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, r := range rows {
		b.WriteString(fmt.Sprintf("| %s | ✅ | %s | %s | %s |\n",
			r.Display, hwCell(r.Res["webgpu"]), hwCell(r.Res["cuda"]), hwCell(r.Res["metal"])))
	}

	// Curated footnotes — load-time fit facts the arch taxonomy can't (and shouldn't) know.
	b.WriteString("\nResident acceleration above is CAPABILITY (does the backend implement the family's\n")
	b.WriteString("features). Two load-time notes the taxonomy does not encode:\n\n")
	b.WriteString("- **Memory fit:** Metal Mistral-7B needs > 16 GB unified memory (int8 + int4); MoE\n")
	b.WriteString("  residency is unified-memory-bound.\n")
	b.WriteString("- **Precision policy:** Nemotron-H resident is int4-only by default (int8 is opt-in via\n")
	b.WriteString("  `GOINFER_SSM_RESIDENT`) — a precision choice applied at load, not a capability.\n")
	b.WriteString("- **Granite-4.0-H's CPU row is the SAME env var, a DIFFERENT gate (N-94, docs/audit-2026-09-10.md).**\n")
	b.WriteString("  `GOINFER_SSM_RESIDENT` is Nemotron-H's precision knob above, but for Granite-4.0-H it is an\n")
	b.WriteString("  ELIGIBILITY gate inside `Architecture.decodeRunnerEligible()` itself, still parity-bring-up-guarded\n")
	b.WriteString("  off by default — this table's generator pins it empty, so every column reads CPU regardless of\n")
	b.WriteString("  backend capability. WebGPU already declares `FeatSSM`; the gap here is the gate not yet being\n")
	b.WriteString("  lifted, not a missing kernel. Set the env var non-empty to see what each backend actually admits.\n")
	b.WriteString("- **Nemotron-H's row is generated from a DENSE representative config.** Real, downloadable\n")
	b.WriteString("  Nemotron 3 Nano and 3.5 Lightning checkpoints add a fourth per-layer block kind (MoE\n")
	b.WriteString("  FFN) this representative config never exercises — WebGPU implements it (G7 part 2,\n")
	b.WriteString("  docs/tasks/task-gpu-paths-2026-09.md); CUDA and Metal still decline it, CPU-only. `DecodePath()`\n")
	b.WriteString("  names this specific per-checkpoint gap for a loaded model; this table cannot, since its\n")
	b.WriteString("  rows are one per architecture, not per checkpoint.\n")
	b.WriteString("- **Gemma 4's row is generated from a representative that is not an E-model.** The small E-models\n")
	b.WriteString("  (E2B, E4B: per-layer embeddings, cross-layer shared KV, variable FFN width) carry the\n")
	b.WriteString("  `gemma4-e-model` feature, which Metal (S1, 2026-10-06) and CUDA (S1 on CUDA, 2026-10-07) declare and\n")
	b.WriteString("  WebGPU does not, so they run resident on Metal and CUDA and on the CPU under WebGPU (a WebGPU run\n")
	b.WriteString("  prints `webgpu does not implement [gemma4-e-model]`). The dense models and the 26B-A4B are\n")
	b.WriteString("  resident as the row says. `DecodePath()` names the gap for a loaded model.\n")
	b.WriteString("- **Command-R, Command-R7B (Aya) and GLM-OCR run on the CPU under WebGPU for a stated reason.** Their\n")
	b.WriteString("  rotary embedding is GPT-J PAIRWISE (dims 2d, 2d+1); WebGPU's rope kernels are the NeoX half-split\n")
	b.WriteString("  (d, d+half), so it does not declare `pairwise-rope` / `pairwise-mrope`. Running them on the NeoX\n")
	b.WriteString("  kernels is exact at position 0 and wrong from position 1 with no error (measured 2026-10-01 on the\n")
	b.WriteString("  CUDA resident before its pairwise kernels existed: real Command-R7B and Aya-expanse-8B at int4, worst\n")
	b.WriteString("  per-position cosine -0.075 / -0.041 against the CPU). CUDA has `cuda/rope_pairwise.cu` and Metal its\n")
	b.WriteString("  twins since 2026-10-09 (docs/tasks/task-metal-pairwise-rope-2026-10.md); a WebGPU row returns once it\n")
	b.WriteString("  has pairwise rope kernels and a resident-vs-CPU gate on peaked attention.\n")
	b.WriteString(verified)
	return []byte(b.String())
}

// TestHardwareMatrix_fresh regenerates the table in memory and fails if the committed
// docs/hardware-matrix.md is stale. Model-free → runs in CI, so a ResidentBackendFeatures or
// arch-flag change must update the table or go red. `-update` rewrites it.
func TestHardwareMatrix_fresh(t *testing.T) {
	rows, err := buildHardwareRows(t)
	if err != nil {
		t.Fatalf("build hardware matrix: %v", err)
	}
	md := renderHardwareMD(rows, mustVerifiedOn(t))
	if *updateMatrix {
		if err := os.WriteFile(hwMatrixPath, md, 0o644); err != nil {
			t.Fatalf("write %s: %v", hwMatrixPath, err)
		}
		t.Logf("wrote %s", hwMatrixPath)
		return
	}
	got, err := os.ReadFile(hwMatrixPath)
	if err != nil {
		t.Fatalf("read %s: %v (hardware matrix stale — regenerate: go test ./decoder -run HardwareMatrix -update)", hwMatrixPath, err)
	}
	// stripCR before comparing: the generated md is always LF, but a Windows checkout with no eol pin stores the committed
	// doc as CRLF, so a bare bytes.Equal would report it stale on line endings alone. .gitattributes pins these docs to
	// eol=lf; this is the other half, so the gate passes under any git autocrlf setting.
	if !bytes.Equal(stripCR(got), md) {
		t.Fatalf("%s out of date — hardware matrix stale — regenerate: go test ./decoder -run HardwareMatrix -update", hwMatrixPath)
	}
}

// stripCR removes carriage returns so a generated-doc freshness comparison is line-ending agnostic. Shared by the
// hardware- and capability-matrix gates.
func stripCR(b []byte) []byte { return bytes.ReplaceAll(b, []byte{'\r'}, nil) }

// TestHardwareMatrix_breakItFirst proves the freshness gate is not vacuous: drop a feature a
// declared family needs, and confirm (a) ResidentEligible flips that cell ✅→CPU and (b) the
// regenerated table diverges from the committed one (so TestHardwareMatrix_fresh would go RED).
// Same discipline as the parity/NaN gates. Reverts the mutation.
func TestHardwareMatrix_breakItFirst(t *testing.T) {
	impl := residentBackendFeatures["cuda"]
	if !impl[FeatSlidingWindow] {
		t.Skip("cuda no longer declares FeatSlidingWindow — pick another feature")
	}
	// Mistral needs sliding-window; with it declared, cuda is resident-eligible.
	arch, _, err := resolveArchitecture(representativeConfig("mistral"))
	if err != nil {
		t.Fatalf("resolve mistral: %v", err)
	}
	if !ResidentEligible(arch, "cuda") {
		t.Fatal("precondition: cuda should be resident-eligible for mistral before the break")
	}
	committed := renderHardwareMD(mustRows(t), mustVerifiedOn(t))

	delete(impl, FeatSlidingWindow) // BREAK
	defer func() { impl[FeatSlidingWindow] = true }()

	if ResidentEligible(arch, "cuda") {
		t.Error("cuda still resident-eligible for mistral after dropping FeatSlidingWindow — predicate is vacuous")
	}
	broken := renderHardwareMD(mustRows(t), mustVerifiedOn(t))
	if bytes.Equal(broken, committed) {
		t.Error("regenerated table is UNCHANGED after dropping a declared feature — the freshness gate is vacuous")
	}
}

func mustRows(t *testing.T) []hwRow {
	t.Helper()
	rows, err := buildHardwareRows(t)
	if err != nil {
		t.Fatalf("build hardware matrix: %v", err)
	}
	return rows
}

// Verified on (hardware-coverage H6, docs/tasks/task-hardware-coverage-2026-10.md): the table above is CAPABILITY. This section is what has actually RUN, generated from the H0 census
// (docs/hardware-coverage.json), so it cannot say more than the census records and goes stale, and red here, the moment a record is added. The census is per hardware-selected code path, not
// per model family, so the section is a machine table and a never-executed list, not a per-family column; a per-family cell would have to be invented.
type censusFile struct {
	Entries []struct {
		ID           string `json:"id"`
		Gate         string `json:"gate"`
		LastExecuted []struct {
			Machine string `json:"machine"`
			Date    string `json:"date"`
			How     string `json:"how"`
		} `json:"last_executed"`
	} `json:"entries"`
}

const censusPath = "../docs/hardware-coverage.json"

func mustVerifiedOn(t *testing.T) string {
	t.Helper()
	raw, err := os.ReadFile(censusPath)
	if err != nil {
		t.Fatalf("read %s: %v", censusPath, err)
	}
	var c censusFile
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("parse %s: %v", censusPath, err)
	}
	return renderVerifiedOn(c)
}

func renderVerifiedOn(c censusFile) string {
	type mach struct {
		hows   map[string]bool
		ids    map[string]bool
		latest string
	}
	var order []string
	byMachine := map[string]*mach{}
	var never []int
	for i, e := range c.Entries {
		if len(e.LastExecuted) == 0 {
			never = append(never, i)
			continue
		}
		for _, r := range e.LastExecuted {
			m, ok := byMachine[r.Machine]
			if !ok {
				m = &mach{hows: map[string]bool{}, ids: map[string]bool{}}
				byMachine[r.Machine] = m
				order = append(order, r.Machine)
			}
			m.hows[r.How] = true
			m.ids[e.ID] = true
			if r.Date > m.latest {
				m.latest = r.Date
			}
		}
	}
	var b strings.Builder
	b.WriteString("\n## Verified on: what has actually run\n\n")
	b.WriteString("The table above is what each backend IMPLEMENTS. This section is what has actually EXECUTED, generated from the hardware census (`docs/hardware-coverage.json`), which records for each\n")
	b.WriteString("hardware-selected code path (a CPU feature tier, a GPU architecture, a memory threshold, an OS) where it last ran. It is per path, not per model family, so it does not fill the table above.\n")
	b.WriteString("Anything not listed here has not run on the machines below, and is guarded only by the startup self-tests (`docs/server.md`), which check the kernels on the machine they run on.\n\n")
	b.WriteString("How it ran: **native** is real hardware; **ci-pool** is a GitHub runner whose CPU the run does not name; **forced** is a build tag making the code take a narrower path than the machine has;\n")
	b.WriteString("**emulated** is Intel SDE or QEMU. The census counts paths, so a machine with a high count is not thereby \"verified\" for every model.\n\n")
	b.WriteString("| Machine | How it ran | Paths with a record | Latest record |\n|---|---|---|---|\n")
	for _, name := range order {
		m := byMachine[name]
		var hows []string
		for h := range m.hows {
			hows = append(hows, h)
		}
		sort.Strings(hows)
		b.WriteString(fmt.Sprintf("| %s | %s | %d | %s |\n", strings.ReplaceAll(name, "|", "/"), strings.Join(hows, ", "), len(m.ids), m.latest))
	}
	b.WriteString(fmt.Sprintf("\n**%d of %d hardware-selected paths have no record of ever executing:**\n\n", len(never), len(c.Entries)))
	for _, i := range never {
		b.WriteString(fmt.Sprintf("- `%s`: %s\n", c.Entries[i].ID, c.Entries[i].Gate))
	}
	return b.String()
}

// TestVerifiedOn_followsTheCensus proves the section is not vacuous: removing one record moves a path to the never-executed list and changes the text, and a path with no records is named.
func TestVerifiedOn_followsTheCensus(t *testing.T) {
	var c censusFile
	raw, err := os.ReadFile(censusPath)
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatal(err)
	}
	full := renderVerifiedOn(c)
	for _, e := range c.Entries {
		if len(e.LastExecuted) == 0 && !strings.Contains(full, "`"+e.ID+"`") {
			t.Errorf("never-executed path %s is not named in the section", e.ID)
		}
	}
	for i := range c.Entries {
		if len(c.Entries[i].LastExecuted) > 0 {
			id := c.Entries[i].ID
			saved := c.Entries[i].LastExecuted
			c.Entries[i].LastExecuted = nil
			mutated := renderVerifiedOn(c)
			c.Entries[i].LastExecuted = saved
			if mutated == full || !strings.Contains(mutated, "`"+id+"`") {
				t.Errorf("dropping every record of %s did not move it to the never-executed list", id)
			}
			break
		}
	}
}
