package decoder

// Generated model × hardware matrix (docs/task-hardware-matrix.md).
//
// Mirrors capability_matrix_test.go's registry walk, but the columns are one thing: does each
// backend run each family on its RESIDENT (GPU) decode path? The cells are 100% derived from
// decoder.ResidentEligible (arch flags + the shared feature taxonomy) — the SAME predicate the
// runtime admits on — so the published "on what hardware" table can never silently drift from
// behavior. Model-free (no weights), so it runs in CI: a backend-feature change either updates
// docs/hardware-matrix.md or turns the build red (TestHardwareMatrix_fresh).
//
// Run `go test ./decoder -run HardwareMatrix -update` to regenerate; the plain run is the gate.

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
)

const hwMatrixPath = "../docs/hardware-matrix.md"
const hwMatrixHeader = "<!-- GENERATED by go test ./decoder -run HardwareMatrix -update — DO NOT EDIT -->"

// residentBackends are the GPU columns, in display order. cpu is implicit (always ✅).
var residentBackends = []string{"webgpu", "cuda", "metal"}

// hwRow is one model family's resident eligibility per backend, keyed by the resolved
// Architecture.Name (aliases that share an adapter collapse to one row).
type hwRow struct {
	Display string
	Res     map[string]bool // backend → ResidentEligible
}

func buildHardwareRows(t *testing.T) ([]hwRow, error) {
	t.Helper()
	keys := make([]string, 0, len(registry))
	for k := range registry {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	rows := map[string]*hwRow{}
	for _, mt := range keys {
		cfg := representativeConfig(mt)
		if cfg == nil {
			return nil, fmt.Errorf("model_type %q has no representativeConfig", mt)
		}
		doc, ok := familyDocs[mt]
		if !ok {
			return nil, fmt.Errorf("model_type %q has no familyDoc", mt)
		}
		arch, _, err := resolveArchitecture(cfg)
		if err != nil {
			return nil, fmt.Errorf("model_type %q failed to resolve: %w", mt, err)
		}
		if _, exists := rows[arch.Name]; exists {
			continue
		}
		res := map[string]bool{}
		for _, be := range residentBackends {
			res[be] = ResidentEligible(arch, be)
		}
		rows[arch.Name] = &hwRow{Display: doc.DisplayName, Res: res}
	}

	out := make([]hwRow, 0, len(rows))
	for _, r := range rows {
		out = append(out, *r)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Display < out[j].Display })
	return out, nil
}

func hwCell(resident bool) string {
	if resident {
		return "✅ resident"
	}
	return "CPU"
}

func renderHardwareMD(rows []hwRow) []byte {
	var b strings.Builder
	b.WriteString(hwMatrixHeader + "\n\n")
	b.WriteString("# goinfer model × hardware matrix\n\n")
	b.WriteString("Every family runs on the pure-Go CPU path; the GPU columns show resident\n")
	b.WriteString("acceleration with automatic, correctness-guaranteed CPU fallback (a backend that\n")
	b.WriteString("does not implement a family's features DECLINES to the staged/CPU path rather than\n")
	b.WriteString("running it silently wrong). Generated from `decoder.ResidentEligible` — arch flags\n")
	b.WriteString("plus the shared feature taxonomy, the single source of truth the runtime admits on.\n")
	b.WriteString("Regenerate with `go test ./decoder -run HardwareMatrix -update`.\n\n")

	b.WriteString("| Family | CPU | WebGPU | CUDA | Metal |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, r := range rows {
		b.WriteString(fmt.Sprintf("| %s | ✅ | %s | %s | %s |\n",
			r.Display, hwCell(r.Res["webgpu"]), hwCell(r.Res["cuda"]), hwCell(r.Res["metal"])))
	}

	// Curated footnotes — load-time fit facts the arch taxonomy can't (and shouldn't) know.
	b.WriteString("\nResident acceleration above is CAPABILITY (does the backend implement the family's\n")
	b.WriteString("features). Two load-time notes the taxonomy does not encode:\n\n")
	b.WriteString("- **Memory fit:** Metal Mistral-7B needs > 16 GB unified memory (int8 + int4); MoE\n")
	b.WriteString("  residency is unified-memory-bound.\n")
	b.WriteString("- **Precision policy:** Nemotron-H resident is int4-only by default (int8 is opt-in via\n")
	b.WriteString("  `GOINFER_SSM_RESIDENT`) — a precision choice applied at load, not a capability.\n")
	return []byte(b.String())
}

// TestHardwareMatrix_fresh regenerates the table in memory and fails if the committed
// docs/hardware-matrix.md is stale. Model-free → runs in CI, so a ResidentBackendFeatures or
// arch-flag change must update the table or go red. `-update` rewrites it.
func TestHardwareMatrix_fresh(t *testing.T) {
	rows, err := buildHardwareRows(t)
	if err != nil {
		t.Fatalf("build hardware matrix: %v", err)
	}
	md := renderHardwareMD(rows)
	if *updateMatrix {
		if err := os.WriteFile(hwMatrixPath, md, 0o644); err != nil {
			t.Fatalf("write %s: %v", hwMatrixPath, err)
		}
		t.Logf("wrote %s", hwMatrixPath)
		return
	}
	got, err := os.ReadFile(hwMatrixPath)
	if err != nil {
		t.Fatalf("read %s: %v (hardware matrix stale — regenerate: go test ./decoder -run HardwareMatrix -update)", hwMatrixPath, err)
	}
	// stripCR before comparing: the generated md is always LF (Go "\n" literals), but a Windows
	// checkout with no eol pin stores the committed doc as CRLF, so a bare bytes.Equal would report
	// it "stale" on line endings alone. .gitattributes pins these docs to eol=lf; this is the
	// other half, so the gate passes under any git autocrlf setting. (Windows CI would trip it —
	// goinfer's is ubuntu+macos only, so this is a latent bug, not an active one.)
	if !bytes.Equal(stripCR(got), md) {
		t.Fatalf("%s out of date — hardware matrix stale — regenerate: go test ./decoder -run HardwareMatrix -update", hwMatrixPath)
	}
}

// stripCR removes carriage returns so a generated-doc freshness comparison is line-ending agnostic
// (mirrors aikit cfda968). Shared by the hardware- and capability-matrix gates.
func stripCR(b []byte) []byte { return bytes.ReplaceAll(b, []byte{'\r'}, nil) }

// TestHardwareMatrix_breakItFirst proves the freshness gate is not vacuous: drop a feature a
// declared family needs, and confirm (a) ResidentEligible flips that cell ✅→CPU and (b) the
// regenerated table diverges from the committed one (so TestHardwareMatrix_fresh would go RED).
// Same discipline as the parity/NaN gates. Reverts the mutation.
func TestHardwareMatrix_breakItFirst(t *testing.T) {
	impl := ResidentBackendFeatures["cuda"]
	if !impl[FeatSlidingWindow] {
		t.Skip("cuda no longer declares FeatSlidingWindow — pick another feature")
	}
	// Mistral needs sliding-window; with it declared, cuda is resident-eligible.
	arch, _, err := resolveArchitecture(representativeConfig("mistral"))
	if err != nil {
		t.Fatalf("resolve mistral: %v", err)
	}
	if !ResidentEligible(arch, "cuda") {
		t.Fatal("precondition: cuda should be resident-eligible for mistral before the break")
	}
	committed := renderHardwareMD(mustRows(t))

	delete(impl, FeatSlidingWindow) // BREAK
	defer func() { impl[FeatSlidingWindow] = true }()

	if ResidentEligible(arch, "cuda") {
		t.Error("cuda still resident-eligible for mistral after dropping FeatSlidingWindow — predicate is vacuous")
	}
	broken := renderHardwareMD(mustRows(t))
	if bytes.Equal(broken, committed) {
		t.Error("regenerated table is UNCHANGED after dropping a declared feature — the freshness gate is vacuous")
	}
}

func mustRows(t *testing.T) []hwRow {
	t.Helper()
	rows, err := buildHardwareRows(t)
	if err != nil {
		t.Fatalf("build hardware matrix: %v", err)
	}
	return rows
}
