package decoder

import (
	"bytes"
	"crypto/sha256"
	"hash/crc32"
	"os"
	"testing"

	"github.com/townsendmerino/aikit/embed"
)

// TestQwen35StreamingTranscode_matchesResident is the correctness gate
// docs/task-zeno-compare.md's streaming-transcode fix owes: the qwen35
// dedicated loader's per-layer output must be BYTE-IDENTICAL whether built
// via the old always-parallel/always-resident path (buildWeightsFromGGUF
// with sink=nil, then SerializeWeights) or the new streaming path
// (buildWeightsFromGGUF with a real sink, sequential build-write-release per
// layer) — a control-flow change, not a numerics one.
//
// No tiny qwen35 GGUF fixture exists (testdata/qwen3_5_moe-tiny is
// safetensors, generated by scripts/pin_qwen3_5_forward.py, not GGUF). Rather
// than build new fixture-generation tooling, this clones the real
// architecture with NumLayers reduced to 2 and points both code paths at the
// SAME real Qwen3.5-35B-A3B GGUF (the one downloaded for docs/task-zeno-
// compare.md) — only layers 0-1's real tensors get touched either way, small
// enough to safely run the old resident path for comparison (the whole
// reason a new tiny fixture would otherwise be needed).
//
//	GOINFER_STUBPROBE_GGUF=~/models/Qwen3.5-35B-A3B-Q4_K_M.gguf \
//	go test ./decoder -run TestQwen35StreamingTranscode_matchesResident -v
func TestQwen35StreamingTranscode_matchesResident(t *testing.T) {
	path := os.Getenv("GOINFER_STUBPROBE_GGUF")
	if path == "" {
		t.Skip("set GOINFER_STUBPROBE_GGUF to a real qwen3.5-35B-A3B GGUF path")
	}

	// Fresh GGUF handle + cfg + arch PER PATH — buildWeightsFromGGUF is called
	// twice in this test (once per path) and Config/Architecture may carry
	// pointer/slice fields that a shallow `w.Cfg = *cfg` copy shares; re-deriving
	// everything from scratch for each call rules out cross-call state leakage
	// as a source of any observed difference, so a real difference (if any)
	// can only be the code path itself.
	openFresh := func() (*embed.GGUFFile, *Config, *Architecture) {
		g, err := embed.OpenGGUFMmap(path)
		if err != nil {
			t.Fatalf("open gguf: %v", err)
		}
		t.Cleanup(func() { g.Close() })
		cfg, err := ggufConfig(g)
		if err != nil {
			t.Fatalf("gguf config: %v", err)
		}
		if err := validateGGUFDims(cfg); err != nil {
			t.Fatalf("validate dims: %v", err)
		}
		arch, _, err := resolveArchitecture(cfg)
		if err != nil {
			t.Fatalf("resolve architecture: %v", err)
		}
		if arch.qwen35 == nil {
			t.Fatalf("fixture at %s did not resolve to the qwen35 family — wrong model for this gate", path)
		}
		// Reduce to 2 layers: loadQ35's tensor names are blk.<i>. for i in
		// [0, NumLayers), so this only touches the real GGUF's own layers 0-1 —
		// small enough to run the old (parallel, resident) path safely, and a
		// genuine subset of the real model's real tensors, not synthetic data.
		//
		// cfg.NumLayers (not just arch.NumLayers) must shrink too: it's what gets
		// marshaled into the .giw header's cfgJSON, and LoadSerializedWeights
		// re-resolves the architecture from THAT round-tripped config — a
		// mismatch there (blob has 2 layers, decoded arch expects 40) fails
		// validateShapes/qwen3_5_moe's own LayerTypes-length check regardless of
		// how many layers the blob itself actually carries.
		cfg.NumLayers = 2
		if len(cfg.LayerTypes) > 2 {
			cfg.LayerTypes = cfg.LayerTypes[:2]
		}
		arch.NumLayers = 2
		return g, cfg, arch
	}

	q := quantInt4

	// Old path: sink=nil (always parallel, always resident), then
	// SerializeWeights (buffer mode, whole-buffer CRC) — the exact code path
	// this fix removes for qwen35.
	gOld, cfgOld, archOld := openFresh()
	wOld, err := buildWeightsFromGGUF(cfgOld, archOld, gOld, q, false, nil, "")
	if err != nil {
		t.Fatalf("old path build: %v", err)
	}
	oldBytes, err := SerializeWeights(wOld, "streaming-gate-test")
	if err != nil {
		t.Fatalf("old path serialize: %v", err)
	}

	// New path: sink != nil, buffer mode (giwWriter{} with sink field unset —
	// distinct from buildWeightsFromGGUF's OWN sink PARAMETER, which is this
	// non-nil *giwWriter), sequential build-write-release per layer. Manual
	// CRC finalize matches SerializeWeights' own buffer-mode convention
	// (whole-buffer CRC32, not the running-CRC stream-mode variant
	// StreamTranscodeGGUF uses when writing to a real file).
	gNew, cfgNew, archNew := openFresh()
	wr := &giwWriter{}
	if _, err := buildWeightsFromGGUF(cfgNew, archNew, gNew, q, false, wr, "streaming-gate-test"); err != nil {
		t.Fatalf("new path build: %v", err)
	}
	wr.u32(crc32.ChecksumIEEE(wr.buf))
	newBytes := wr.buf

	// Both bundles must decode cleanly — this alone validates each buffer's own
	// trailing CRC, so the byte-span comparison below never needs to look at it.
	wOldDecoded, err := LoadSerializedWeights(oldBytes)
	if err != nil {
		t.Fatalf("old path decode: %v", err)
	}
	wNewDecoded, err := LoadSerializedWeights(newBytes)
	if err != nil {
		t.Fatalf("new path decode: %v", err)
	}

	// The two bundles are NOT expected to be raw byte-identical: writeHeadGlobals
	// gates the baked quantLabel field on data availability (B11, serialize.go:170-
	// 185), not on which writer is in use. The old path fully materializes every
	// layer before ever calling writeHeadGlobals (via SerializeWeights on an
	// already-complete *Weights), so quantLabel() sees real tensor kinds and bakes
	// "int4mix". The new path calls writeHeadGlobals on a freshly allocated,
	// all-zero Layers slice BEFORE the first layer streams in — genuinely true
	// streaming, exactly like every other already-streaming family — so
	// hasPopulatedLayers() is false and the baked label is correctly left "" to be
	// re-inferred at load time. That's the one designed difference; the gate below
	// confirms it is the ONLY one and that both resolve to the same label once loaded.
	splitAtLabel := func(data []byte) (before []byte, label string, after []byte) {
		r := &giwReader{data: data}
		r.rawN(len(giwMagic))
		r.u32()        // version
		r.u32()        // quantMode
		r.str()        // id
		r.bytesField() // cfgJSON
		start := r.off
		label = r.str()
		return data[:start], label, data[r.off:]
	}
	oldBefore, oldLabel, oldAfter := splitAtLabel(oldBytes)
	newBefore, newLabel, newAfter := splitAtLabel(newBytes)

	if !bytes.Equal(oldBefore, newBefore) {
		t.Fatalf("header before the quantLabel field differs (old=%d new=%d bytes)", len(oldBefore), len(newBefore))
	}
	if oldLabel != "int4mix" {
		t.Fatalf("old (resident) path should bake a resolved label, got %q", oldLabel)
	}
	if newLabel != "" {
		t.Fatalf("new (streaming) path should defer the label (writeHeadGlobals runs before any layer streams in), got %q", newLabel)
	}
	// Drop the trailing 4-byte CRC from each: it's computed over the WHOLE buffer,
	// so the label field's own length difference legitimately changes it on both
	// sides even though every actual tensor byte agrees. Each buffer's CRC was
	// already checked for internal self-consistency by the successful
	// LoadSerializedWeights decode above.
	oldAfter = oldAfter[:len(oldAfter)-4]
	newAfter = newAfter[:len(newAfter)-4]

	if !bytes.Equal(oldAfter, newAfter) {
		n := min(len(oldAfter), len(newAfter))
		firstDiff := -1
		for i := range n {
			if oldAfter[i] != newAfter[i] {
				firstDiff = i
				break
			}
		}
		if firstDiff < 0 {
			t.Fatalf("everything after the quantLabel field differs only in length: old=%d new=%d bytes", len(oldAfter), len(newAfter))
		}
		lo, hi := max(0, firstDiff-8), min(n, firstDiff+24)
		t.Fatalf("bytes after the quantLabel field differ at offset %d (of %d): old=% x new=% x", firstDiff, n, oldAfter[lo:hi], newAfter[lo:hi])
	}

	// Both must resolve to the same live label once loaded (LoadSerializedWeights
	// always fully populates Layers regardless of how the bundle was written, so
	// quantLabel()'s live-inference fallback sees identical tensor kinds either way).
	if oldGot, newGot := wOldDecoded.quantLabel(), wNewDecoded.quantLabel(); oldGot != newGot {
		t.Fatalf("decoded quantLabel mismatch: old=%q new=%q", oldGot, newGot)
	}

	t.Logf("identical apart from the designed baked-label difference (old %d bytes sha256 %x, new %d bytes sha256 %x)",
		len(oldBytes), sha256.Sum256(oldBytes), len(newBytes), sha256.Sum256(newBytes))
}
