package decoder

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/townsendmerino/goinfer/multimodal"
)

// S8 (docs/tasks/task-multimodal-support-2026-10.md, "S8, plan and gates"): the images-and-audio support table in
// docs/multimodal.md and the README, generated here. Every tower / decoder cell is computed from code:
//   - tower: GPU when the backend's build declares that tower family (multimodal.DeclaredTower; each backend module's test
//     proves its live registrations equal the declaration);
//   - decoder: GPU when an image turn decodes on the backend's resident (imageTurnDecodesResident: ResidentEligible, the
//     hybrid image prefill declaration, Gemma 4's rule).
//
// The notes are what the code cannot answer (validation, memory, speed), each with a date. Regenerate with
// `go test ./decoder -run SupportTable -update`; the test fails when either file's block differs from the generated one.

const (
	supportBegin = "<!-- BEGIN images-and-audio support table: generated by `go test ./decoder -run SupportTable -update` (decoder/support_table_test.go); the cells are computed from code, edit the notes there -->"
	supportEnd   = "<!-- END images-and-audio support table -->"
)

// supportBackends are the table's columns, in order (decoder's backend names; "cpu" is the CPU column).
var supportBackends = []struct{ name, label string }{{"cpu", "CPU"}, {"cuda", "CUDA"}, {"metal", "Metal"}, {"webgpu", "WebGPU"}}

// supportRow is one family of the table: its label, the model_type serve dispatches on, its tower family, the config its
// decoder cells are computed from, and the notes.
type supportRow struct {
	label, modelType, tower string
	cfg                     func(t *testing.T) *Config
	notes                   string
}

func rep(mt string, edit func(*Config)) func(t *testing.T) *Config {
	return func(t *testing.T) *Config {
		c := representativeConfig(mt)
		if c == nil {
			t.Fatalf("no representative config for %q", mt)
		}
		if edit != nil {
			edit(c)
		}
		return c
	}
}

// eModelConfig is an E-model's config.json (testdata/gemma4-emodel-tiny's, inlined: that fixture is gitignored, and CI has
// only tracked files): per-layer inputs (PLE), KV-shared layers and a per-layer head dim, the E2B/E4B shape.
const eModelConfig = `{"attention_bias":false,"attention_k_eq_v":false,"bos_token_id":2,"enable_moe_block":false,"eos_token_id":1,"final_logit_softcapping":30.0,"head_dim":32,"hidden_activation":"gelu_pytorch_tanh","hidden_size":256,"hidden_size_per_layer_input":32,"intermediate_size":256,"layer_types":["sliding_attention","sliding_attention","full_attention","sliding_attention","sliding_attention","full_attention"],"max_position_embeddings":128,"model_type":"gemma4_text","moe_intermediate_size":null,"num_attention_heads":4,"num_experts":null,"num_hidden_layers":6,"num_key_value_heads":1,"num_kv_shared_layers":2,"pad_token_id":0,"per_layer_config":{"2":{"head_dim":64},"5":{"head_dim":64}},"rms_norm_eps":1e-06,"rope_local_base_freq":10000.0,"rope_parameters":{"full_attention":{"partial_rotary_factor":0.25,"rope_theta":1000000.0,"rope_type":"proportional"},"sliding_attention":{"rope_theta":10000.0,"rope_type":"default"}},"rope_theta":1000000.0,"sliding_window":4,"tie_word_embeddings":true,"top_k_experts":null,"use_bidirectional_attention":null,"use_double_wide_mlp":true,"vocab_size":256,"vocab_size_per_layer_input":256}`

func jsonConfig(raw string) func(t *testing.T) *Config {
	return func(t *testing.T) *Config {
		c, err := loadConfig(fstest.MapFS{"config.json": {Data: []byte(raw)}}, "config.json")
		if err != nil {
			t.Fatalf("config: %v", err)
		}
		return c
	}
}

func bidirectional(c *Config) { c.UseBidirectionalAttention = "vision" }

var supportRows = []supportRow{
	{"Gemma 3", "gemma3", multimodal.TowerSigLIP, rep("gemma3", nil),
		"CUDA: float32 tower by default, int8 when the card cannot hold it (2026-10-08); WebGPU: int8 tower. Metal: resident by default on a 16 GB Mac (G-S18a, 2026-10-08)."},
	{"Gemma 4 E2B, E4B", "gemma4", multimodal.TowerGemma4, jsonConfig(eModelConfig),
		"E4B validated on CUDA (2026-10-08), not yet on Metal (2026-10-09)."},
	{"Gemma 4 E2B, E4B audio", "gemma4", multimodal.TowerGemma4Audio, jsonConfig(eModelConfig),
		"One clip per request; 16-bit WAV, any rate (2026-10-09)."},
	{"Gemma 4 26B", "gemma4", multimodal.TowerGemma4, rep("gemma4_unified_text", bidirectional),
		"Tower checked on E2B (2026-10-07)."},
	{"Gemma 4 31B", "gemma4", multimodal.TowerGemma4, rep("gemma4", bidirectional),
		"Validation in flight on nobara (2026-10-09); too large for a 16 GB Mac."},
	{"Qwen2.5-VL", "qwen2_5_vl", multimodal.TowerQwen25VL, rep("qwen2_5_vl", nil), ""},
	{"Qwen3.5+ dense", "qwen3_5", multimodal.TowerQwen3, rep("qwen3_5", nil),
		"A hybrid's image turn decodes resident only where the backend builds its recurrent state (CUDA); text turns are resident where the decoder column of docs/hardware-matrix.md says (2026-10-09)."},
	{"Qwen3.5+ MoE", "qwen3_5_moe", multimodal.TowerQwen3, rep("qwen3_5_moe", nil),
		"Served on CUDA (S6, 2026-10-09)."},
	{"Qwen3-VL", "qwen3_vl", multimodal.TowerQwen3, rep("qwen3_vl", nil),
		"DeepStack. Several images in one message take the CPU prefill and upload (2026-10-09)."},
	{"GLM-OCR", "glm_ocr", multimodal.TowerGlmOcr, rep("glm_ocr", nil),
		"One image per request (2026-10-09)."},
}

// supportCell computes one tower / decoder cell.
func supportCell(t *testing.T, row supportRow, backend string) string {
	if backend == "cpu" {
		return "CPU / CPU"
	}
	tower := "CPU"
	if multimodal.DeclaredTower(backend, row.tower) {
		tower = "GPU"
	}
	cfg := row.cfg(t)
	a, _, err := resolveArchitecture(cfg)
	if err != nil {
		t.Fatalf("%s: resolve: %v", row.label, err)
	}
	dec := "CPU"
	if imageTurnDecodesResident(cfg, a, backend) {
		dec = "GPU"
	}
	return tower + " / " + dec
}

// generateSupportTable renders the block: withNotes for docs/multimodal.md, without for the README.
func generateSupportTable(t *testing.T, withNotes bool) string {
	var b strings.Builder
	b.WriteString(supportBegin + "\n\n")
	b.WriteString("Each cell: where the image or audio **tower** runs / where the **decoder** runs after the image.\n\n")
	head, sep := "| family (`model_type`) |", "|---|"
	for _, be := range supportBackends {
		head += " " + be.label + " |"
		sep += "---|"
	}
	if withNotes {
		head += " notes |"
		sep += "---|"
	}
	b.WriteString(head + "\n" + sep + "\n")
	for _, row := range supportRows {
		line := fmt.Sprintf("| %s (`%s`) |", row.label, row.modelType)
		for _, be := range supportBackends {
			line += " " + supportCell(t, row, be.name) + " |"
		}
		if withNotes {
			line += " " + row.notes + " |"
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n" + supportEnd)
	return b.String()
}

// spliceSupportBlock returns doc with its BEGIN..END block replaced by block, and whether the doc had one.
func spliceSupportBlock(doc, block string) (string, bool) {
	i := strings.Index(doc, supportBegin)
	j := strings.Index(doc, supportEnd)
	if i < 0 || j < i {
		return doc, false
	}
	return doc[:i] + block + doc[j+len(supportEnd):], true
}

// TestSupportTable_fresh (G-S8a): docs/multimodal.md's and the README's support tables equal the generated ones.
func TestSupportTable_fresh(t *testing.T) {
	t.Setenv("GOINFER_SSM_RESIDENT", "") // the hardware matrix's own pin (ResidentEligible's granite gate reads it)
	for _, f := range []struct {
		path      string
		withNotes bool
	}{{"../docs/multimodal.md", true}, {"../README.md", false}} {
		raw, err := os.ReadFile(f.path)
		if err != nil {
			t.Fatal(err)
		}
		want := generateSupportTable(t, f.withNotes)
		got, ok := spliceSupportBlock(string(raw), want)
		if !ok {
			t.Errorf("%s has no support-table block (%q ... %q)", f.path, supportBegin[:30], supportEnd)
			continue
		}
		if *updateMatrix {
			if err := os.WriteFile(f.path, []byte(got), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		if !bytes.Equal(raw, []byte(got)) {
			t.Errorf("%s: the support table is stale; regenerate with `go test ./decoder -run SupportTable -update`\n%s", f.path, want)
		}
	}
}

// TestSupportTable_plantedDefects (G-S8b): the drift each piece of the check exists for turns a cell, so the
// generated-and-compared table would go red. Each mutation is applied to the computation, not to the file.
func TestSupportTable_plantedDefects(t *testing.T) {
	t.Setenv("GOINFER_SSM_RESIDENT", "")
	byLabel := map[string]supportRow{}
	for _, r := range supportRows {
		byLabel[r.label] = r
	}
	// This morning's real error: Qwen3.5+ on Metal decoding an image turn on the GPU. The cell must read CPU, and a
	// Metal hybrid image prefill (a declaration that would make it GPU) is not declared.
	if got := supportCell(t, byLabel["Qwen3.5+ dense"], "metal"); got != "GPU / CPU" {
		t.Errorf("Qwen3.5+ dense on Metal: %q, want GPU / CPU (the tower is Metal's, the image turn decodes on the CPU)", got)
	}
	if HybridImagePrefillDeclared("metal", false) {
		t.Error("a hybrid image prefill is declared for Metal, which implements none")
	}
	if got := supportCell(t, byLabel["Qwen3.5+ dense"], "cuda"); got != "GPU / GPU" {
		t.Errorf("Qwen3.5+ dense on CUDA: %q, want GPU / GPU (CUDA builds a dense hybrid's state in its image prefill)", got)
	}
	// A WebGPU Gemma 4 tower is not declared: the cell must read CPU for the tower.
	if got := supportCell(t, byLabel["Gemma 4 E2B, E4B"], "webgpu"); !strings.HasPrefix(got, "CPU / ") {
		t.Errorf("Gemma 4 on WebGPU: %q, want a CPU tower", got)
	}
	// A causal, non-E Gemma 4 decodes on the CPU after an image, whatever the backend.
	causal := supportRow{label: "causal Gemma 4", tower: multimodal.TowerGemma4, cfg: rep("gemma4", nil)}
	if got := supportCell(t, causal, "cuda"); strings.HasSuffix(got, "/ GPU") {
		t.Errorf("a causal, non-E Gemma 4 on CUDA: %q, want a CPU decoder after an image", got)
	}
	// A README cell that differs from the doc's: the two blocks share every cell, so one edited cell differs.
	doc, readme := generateSupportTable(t, true), generateSupportTable(t, false)
	if !strings.Contains(doc, "| Qwen3.5+ dense (`qwen3_5`) | CPU / CPU | GPU / GPU | GPU / CPU | CPU / CPU |") ||
		!strings.Contains(readme, "| Qwen3.5+ dense (`qwen3_5`) | CPU / CPU | GPU / GPU | GPU / CPU | CPU / CPU |") {
		t.Errorf("the README and doc blocks do not carry the same Qwen3.5+ row:\n%s\n%s", doc, readme)
	}
	mutated, _ := spliceSupportBlock(supportBegin+"\n"+supportEnd, strings.Replace(readme, "GPU / CPU", "GPU / GPU", 1))
	if mutated == readme {
		t.Error("a mutated README cell compares equal: the freshness check could not see it")
	}
}
