package clef

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// testdata/render_cases.json holds inputs and the output of REAL Python 3 json.dumps(v, ensure_ascii=False, separators=(",", ":"),
// sort_keys=True) for each (regenerated by scripts/pin_clef_render_cases.py). The cases are the ones Go's encoding/json gets wrong: float spelling, control-character escapes, key order over
// non-ASCII keys, a repeated key, integers past 2^53, and characters Go would escape (<, >, &, U+2028).
func TestRender_matchesPythonJSONDumps(t *testing.T) {
	raw, err := os.ReadFile("testdata/render_cases.json")
	if err != nil {
		t.Fatalf("no cases (a skip would hide this): %v", err)
	}
	var cases []struct{ In, Out string }
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}
	if len(cases) < 10 {
		t.Fatalf("only %d cases", len(cases))
	}
	for _, c := range cases {
		v, err := parse([]byte(c.In))
		if err != nil {
			t.Errorf("%s: %v", c.In, err)
			continue
		}
		got, err := dumps(v)
		if err != nil {
			t.Errorf("%s: %v", c.In, err)
			continue
		}
		if got != c.Out {
			t.Errorf("input  %s\n   got  %s\n   want %s", c.In, got, c.Out)
		}
	}
}

// The reference's render() returns a string as is: no quotes, no escaping.
func TestRender_stringIsReturnedAsIs(t *testing.T) {
	v, err := parse([]byte(`"line\n\"quoted\" é"`))
	if err != nil {
		t.Fatal(err)
	}
	got, _ := render(v)
	if got != "line\n\"quoted\" é" {
		t.Errorf("got %q", got)
	}
}

// Python's json.loads accepts what JSON does not; this port refuses it rather than build a prompt the reference would have built
// differently.
func TestParse_refusesWhatItCannotRepresent(t *testing.T) {
	for _, in := range []string{`NaN`, `[Infinity]`, `"\ud800"`, `"\udc00x"`, `{"a":`, "\"bad \xff utf8\"", `1e999`} {
		v, err := parse([]byte(in))
		if err == nil {
			_, err = dumps(v)
		}
		if err == nil {
			t.Errorf("%q was accepted", in)
		}
	}
	if _, err := parse([]byte(strings.Repeat(" ", 3) + `{"a": [1, 2]}`)); err != nil {
		t.Errorf("surrounding whitespace was refused: %v", err)
	}
}
