#!/usr/bin/env python3
"""doc_review_staleness.py — which docs/tasks/ and docs/prompts/ files need a fresh /doc-review pass.

Each live design record and prompt brief carries a footer:

    <!-- doc-reviewed: YYYY-MM-DD -->

added by a /doc-review pass (or a manual confirmation) once every claim in the file has been
checked against the tree. This script answers the question a full re-sweep costs too much to ask
every time: has anything moved since that date?

A doc's own last-edit date is a weak signal — the failure mode /doc-review exists to catch is a
doc sitting untouched while the CODE it describes drifts out from under it. So this checks two
things per doc, not one:

  1. the doc file itself — did someone edit it without updating the footer?
  2. every file docs/QUEUE.md's citation index says the doc cites — did any of THOSE change?

The citation index already exists (scripts/queue_citation_lint.py maintains it as a pre-push gate)
and already maps every doc to every path:line it points at. Reusing it here means this script asks
exactly the question the doc's own citations claim to be about, not a proxy for it.

SCOPE, DELIBERATELY. Only docs/tasks/*.md, docs/tasks/parked/*.md and docs/prompts/*.md are
checked — the two directories currently under this convention. docs/completed/ is excluded on
purpose: archived docs are frozen records and are not supposed to track the tree (same reasoning
queue_citation_lint.py already applies).

AIKIT CITATIONS ARE NOT CHECKED AGAINST AIKIT'S OWN HISTORY. queue_citation_lint.py's own
path_repos() docstring explains why: a cross-repo citation resolves against the PINNED module
version in go.mod, not against whatever the sibling checkout's working tree happens to be on — so
"aikit changed" is not the right question, and asking it produced exactly the flip-flopping false
reds that function was written to stop (linalg/quant.go:113, "went red TWICE in one day because
aikit committed"). The right question IS checked, though: whether goinfer's own PIN has moved —
`git log -G aikit` on the four go.mod files (root, gpu/, cuda/, metal/) since the footer date. `-G`
matches a regex against each commit's actual diff content, so this catches every real
`deps: bump aikit to vX.Y.Z` commit (confirmed against this tree's own history: `e314e8c2`,
`b505ab6a`, `fbf142ab`, ... all match) plus the occasional feature commit that touches a go.mod
line mentioning aikit for an unrelated reason — a wider net than "only version bumps," which is the
right side to err on for a staleness *hint*, not a hard gate. If the pin moved, that does not by
itself mean a cited aikit symbol changed shape — same as a goinfer file touch doesn't guarantee the
cited line changed — it means "worth a look," which is what this whole script is for.

This is a read-only report. It does not touch any file and is not a push gate — run it by hand
before deciding which docs are worth a fresh /doc-review pass.
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
QUEUE = ROOT / "docs" / "QUEUE.md"

FOOTER_RE = re.compile(r"<!--\s*doc-reviewed:\s*(\d{4}-\d{2}-\d{2})\s*-->")
MARK_BEGIN = "<!-- CITATION-INDEX: generated by scripts/queue_citation_lint.py --update; do not edit by hand -->"
INDEX_ROW_RE = re.compile(r"^\|\s*`([^`]+):(\d+)`\s*\|\s*([^|]*?)\s*\|\s*`(.*)`\s*\|$")

AIKIT_GOMOD_FILES = ["go.mod", "gpu/go.mod", "cuda/go.mod", "metal/go.mod"]
_aikit_bump_cache = {}


def aikit_pin_bump_since(footer_date: str):
    """The most recent commit (short sha, date, subject) on/after footer_date that touched a line
    mentioning "aikit" in one of the four go.mod files, or None if there's been no such commit.
    Memoized per footer_date since the same query repeats across every doc reviewed on the same
    day."""
    if footer_date in _aikit_bump_cache:
        return _aikit_bump_cache[footer_date]
    r = subprocess.run(
        ["git", "log", f"--since={footer_date} 00:00:00", "-G", "aikit",
         "--format=%h\t%ad\t%s", "--date=short", "--", *AIKIT_GOMOD_FILES],
        cwd=ROOT, capture_output=True, text=True,
    )
    lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
    result = None
    if lines:
        sha, date, subject = lines[0].split("\t", 2)
        if date > footer_date:
            result = (sha, date, subject)
    _aikit_bump_cache[footer_date] = result
    return result


def review_scoped_docs():
    out = []
    for base in ("docs/tasks", "docs/prompts"):
        d = ROOT / base
        if d.is_dir():
            out += sorted(p for p in d.rglob("*.md"))
    return out


def last_commit_date(relpath: str):
    """YYYY-MM-DD of the last commit touching relpath, or None if it has no history here
    (uncommitted, or the path citation is stale/wrong — not this script's job to say which)."""
    r = subprocess.run(
        ["git", "log", "-1", "--format=%ad", "--date=short", "--", relpath],
        cwd=ROOT, capture_output=True, text=True,
    )
    d = r.stdout.strip()
    return d or None


def parse_citation_index():
    """doc relpath -> [(cited_path, repo), ...], read from docs/QUEUE.md's generated index."""
    if not QUEUE.exists():
        return {}
    text = QUEUE.read_text()
    if MARK_BEGIN not in text:
        return {}
    idx = {}
    for line in text.split(MARK_BEGIN, 1)[1].splitlines():
        m = INDEX_ROW_RE.match(line.strip())
        if not m:
            continue
        key, _line_no, repo, _content = m.groups()
        if "|" not in key:
            continue
        doc, cited = key.split("|", 1)
        idx.setdefault(doc, []).append((cited, repo))
    return idx


def main() -> int:
    docs = review_scoped_docs()
    citation_idx = parse_citation_index()

    stale, fresh, no_footer = [], [], []

    for doc in docs:
        rel = str(doc.relative_to(ROOT))
        text = doc.read_text(encoding="utf-8", errors="replace")
        m = FOOTER_RE.search(text)
        if not m:
            no_footer.append(rel)
            continue
        footer_date = m.group(1)

        reasons = []
        doc_date = last_commit_date(rel)
        if doc_date and doc_date > footer_date:
            reasons.append(f"the doc itself was edited {doc_date}")

        aikit_cites = []
        for cited, repo in citation_idx.get(rel, []):
            if repo.strip() != "goinfer":
                if repo.strip():
                    aikit_cites.append((cited, repo.strip()))
                continue
            cited_date = last_commit_date(cited)
            if cited_date and cited_date > footer_date:
                reasons.append(f"{cited} touched {cited_date}")

        if aikit_cites:
            bump = aikit_pin_bump_since(footer_date)
            if bump:
                sha, date, subject = bump
                reasons.append(f"aikit pin possibly moved: {sha} {date} \"{subject}\"")

        if reasons:
            stale.append((rel, footer_date, reasons, aikit_cites))
        else:
            fresh.append((rel, footer_date, aikit_cites))

    total = len(docs)
    print(f"doc_review_staleness: {total} file(s) under docs/tasks/ and docs/prompts/.\n")

    if stale:
        print(f"STALE ({len(stale)}) — footer predates a change to the doc or something it cites:")
        for rel, footer_date, reasons, aikit_cites in sorted(stale):
            print(f"  {rel}  (reviewed {footer_date})")
            for reason in reasons:
                print(f"    - {reason}")
        print()

    if no_footer:
        print(f"NO FOOTER ({len(no_footer)}) — never been through a doc-review pass with this tracking:")
        for rel in sorted(no_footer):
            print(f"  {rel}")
        print()

    print(f"FRESH ({len(fresh)}) — nothing has moved since the last review.")
    aikit_touched = [rel for rel, _, aikit_cites in fresh if aikit_cites]
    if aikit_touched:
        print(f"  ({len(aikit_touched)} of these cite aikit paths — checked via whether the aikit pin")
        print("   in go.mod has moved since the review, not against aikit's own commit history; see")
        print("   the module docstring for why.)")

    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
