#!/usr/bin/env python3
"""queue_citation_lint.py — every citation in docs/QUEUE.md must resolve, and its target must match.

Two kinds are checked: COMMIT citations (sha -> subject) and PATH citations (file:line -> the trimmed
content of that line). Both are recorded in a generated index at the bottom of the file and compared
on every run.

WHY THIS EXISTS. `9e5f8fa` was cited in docs/QUEUE.md as the precedent for a goldens-gated deps_hash
refresh — "a metadata field addition re-staled weights.go and the refresh ran 19 goldens". It is
`fix(quant): reject --quant that conflicts with a prequant .giw at startup` and touches the manifest
not at all. The wrong SHA was then repeated several times, from the file, without anyone opening it.

That is what a state document is *for*, and why an error in one is worse than the same error in
conversation: nothing re-derives what a state document asserts. A claim made in passing gets
re-checked when it matters; a claim written into the queue gets cited. So the error propagated with
more confidence than it started with.

The remedy is mechanical. This lint extracts every SHA-looking token from the queue, resolves it, and
compares its subject against a recorded index at the bottom of the file. `--update` regenerates the
index. Three failure modes are covered, and all three were mutation-checked:

  - a SHA that does not resolve  -> fabricated, mistyped, or from a dropped branch
  - a SHA whose subject changed  -> the index is stale, or the citation was always wrong
  - a SHA reachable from NO ref  -> amended away or rebased out; see below

THE THIRD ONE WAS A HOLE IN THIS LINT, found 2026-08-12 by walking into it. `git log -1 <sha>`
succeeds for any object still in the local store, including one no branch or tag points at. Amending
a commit leaves the original in the reflog, so every citation to the old SHA kept passing green while
pointing at history that existed on exactly one machine. Turning the check on found FOUR such
citations already in the queue, all from this campaign's own rebases and amends — they had been green
the whole time.

Worse than a plain false green: it was MACHINE-DEPENDENT. The same citation is a hard red in a fresh
clone, where the orphan was never fetched. A gate whose answer depends on which box ran it is the
Environment class (docs/parity-coverage-policy.md) wearing a gate's clothes — and this one was the
gate written to stop exactly this kind of drift, which is the G-01 shape one level up: the instrument
exempting itself from the property it enforces.

The check is reachability from any ref, not ancestry of HEAD, so a commit legitimately living on
another branch or a tag still passes.

A citation that cannot resolve here but is still legitimate — another repository, a commit that
never left a machine — is declared explicitly:

    <!-- sha-lint: allow <sha> <reason> -->

The reason is mandatory and is printed by the lint. That is the whole mechanism: it does not make
the citation correct, it makes the fact that nobody has verified it VISIBLE, which is the state
9e5f8fa was in for weeks while reading as authoritative.

Deliberately NOT checking that the surrounding prose describes the commit accurately — that is not
mechanisable. It checks the citation, which is the part that was wrong.
"""

import collections
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
QUEUE = ROOT / "docs" / "QUEUE.md"


def live_docs():
    """Every LIVE markdown document, i.e. everything outside docs/completed/.

    The burial folder is deliberately excluded: those are historical records, and their citations are
    SUPPOSED to age with the code they described. Linting them would fight the archival rule and bury
    the live signal in ~300 lines of expected noise. QUEUE.md is checked first because it hosts the
    index.
    """
    out = [QUEUE]
    for f in sorted(ROOT.rglob("*.md")):
        if "/.git/" in str(f) or "docs/completed/" in str(f) or f == QUEUE:
            continue
        # docs/internal/ is EXCLUDED, and the reason is not tidiness. That directory is
        # DELIBERATELY UNCOMMITTED (.gitignore), so every path inside it resolves on exactly one
        # machine and on none of the clones CI or anyone else runs. Linting it produces failures
        # that are structurally unfixable from anywhere but here -- it has already generated
        # local-only false positives -- and a lint that reds on files CI cannot see is a lint people
        # stop reading. That is a worse outcome than the coverage it buys.
        if "docs/internal/" in str(f):
            continue
        out.append(f)
    return out
MARK_BEGIN = "<!-- CITATION-INDEX: generated by scripts/queue_citation_lint.py --update; do not edit by hand -->"
MARK_END = "<!-- /CITATION-INDEX -->"

# 7-40 hex chars delimited by non-word characters. Requires at least one digit AND one letter, which
# is what separates a commit id from an English word like "deffff" or a decimal figure like 1234567.
SHA_RE = re.compile(r"(?<![0-9a-zA-Z_])([0-9a-f]{7,40})(?![0-9a-zA-Z_])")


def looks_like_sha(tok: str) -> bool:
    return any(c.isdigit() for c in tok) and any(c.isalpha() for c in tok)


# The queue legitimately cites SIBLING repositories — aikit's gpu module ships the kernels goinfer
# embeds, so its SHAs appear here as a matter of course. Searching only this repo made a correct
# citation (be049df) look fabricated, which is a false RED and exactly as bad as the false green the
# lint exists to prevent: it would have driven someone to "fix" an accurate reference.
#
# Override with GOINFER_SHA_LINT_REPOS (colon-separated). Absent repos are skipped silently — they
# are a property of the machine, not of the queue.
class SearchError(Exception):
    """A repository could not be searched — distinct from a SHA not being found in it."""


# A commit that still resolves locally but is reachable from no ref: amended away, rebased out, or
# on a deleted branch. Distinct from "does not resolve" because the remedy differs — the citation is
# not fabricated, it points at history that no longer exists anywhere others can see.
ORPHANED = object()

# Where each path citation was answered from, so the scope line can say whether the version-pinned
# resolution ACTUALLY RAN rather than merely being available. A fix that is present but never
# exercised is the exercised-but-never-triggered shape, and this one exists to make a verdict
# reproducible — so "it would have resolved from the module cache" is not good enough to print.
RESOLVED_FROM = collections.Counter()

# Cited commits reachable only from a LOCAL ref — reported as a warning, never a hard failure here.
LOCAL_ONLY = []


def sibling_repos():
    root = QUEUE.parent.parent
    env = os.environ.get("GOINFER_SHA_LINT_REPOS")
    if env:
        # EXPLICITLY named repos are required to be searchable. A typo'd or moved path must be a hard
        # error, not a silent narrowing of the search — that is precisely how be049df, a correct
        # citation contained in six released tags, was reported as fabricated: the aikit path was one
        # level off, `git -C` failed for that reason, and the failure was read as absence.
        out = [str(root)]
        for c in env.split(":"):
            pp = pathlib.Path(c).expanduser()
            if not (pp / ".git").exists():
                raise SearchError(f"GOINFER_SHA_LINT_REPOS names {pp}, which is not a git repository")
            out.append(str(pp))
        return out
    # The DEFAULT sibling is best-effort: its absence is a property of the machine, not of the queue.
    out = [str(root)]
    dflt = (root / ".." / "aikit" / "aikit").resolve()
    if (dflt / ".git").exists():
        out.append(str(dflt))
    return out


def _commit_count(repo: str) -> str:
    r = subprocess.run(["git", "rev-list", "--count", "HEAD"], capture_output=True, text=True, cwd=repo)
    return r.stdout.strip() or "?"


def subject_of(sha: str):
    """Return the subject, or None if the SHA is genuinely absent from every searchable repo.

    Raises SearchError if a repo could not be searched at all. "Could not look" and "looked and did
    not find" are different answers, and conflating them produces a false RED on a correct citation —
    which costs more than a false green, because it prompts someone to change something accurate.
    """
    for repo in sibling_repos():
        probe = subprocess.run(["git", "rev-parse", "--git-dir"],
                               capture_output=True, text=True, cwd=repo)
        if probe.returncode != 0:
            raise SearchError(f"{repo}: not a usable git repository ({probe.stderr.strip()})")
        # A SHALLOW clone cannot answer this question at all. It holds one commit, so every cited
        # SHA "does not resolve" — and reporting 35 accurate citations as fabricated is the exact
        # false red this file's own docstring calls worse than a false green, because it tells
        # someone to go and change references that were right.
        #
        # This is the "could not look" versus "looked and did not find" distinction the rest of
        # this function already makes, applied to the one case that actually shipped: the lint ran
        # in CI under a depth-1 checkout and main was red for 15 consecutive runs.
        shallow = subprocess.run(["git", "rev-parse", "--is-shallow-repository"],
                                 capture_output=True, text=True, cwd=repo)
        if shallow.stdout.strip() == "true":
            raise SearchError(
                f"{repo}: SHALLOW clone — it contains {_commit_count(repo)} commit(s), so no "
                f"citation can be resolved and every one would be reported as fabricated.\n"
                f"  This lint needs full history. In GitHub Actions set:\n"
                f"      - uses: actions/checkout@v4\n"
                f"        with:\n"
                f"          fetch-depth: 0\n"
                f"  Locally: git fetch --unshallow")
        r = subprocess.run(
            ["git", "log", "-1", "--format=%s", sha],
            capture_output=True, text=True, cwd=repo,
        )
        if r.returncode == 0:
            # RESOLVING IS NOT ENOUGH — the commit must be REACHABLE FROM A REF.
            #
            # `git log -1 <sha>` succeeds for any object still in the local store, including one
            # that no branch or tag points at: an amended-away or rebased-out commit survives in
            # the reflog and keeps resolving for as long as gc spares it. Found the honest way —
            # this file's own bump commit was amended, every citation to the old sha kept passing
            # green, and the old sha was by then reachable from nothing.
            #
            # That green was also MACHINE-DEPENDENT, which is the worse half: the same citation is
            # a hard red in a fresh clone, where the orphan was never fetched. A lint whose answer
            # depends on which box ran it is the Environment class (docs/parity-coverage-policy.md)
            # wearing a gate's clothes.
            #
            # So: reachable from any ref, or it does not count. Checked with rev-list rather than
            # `merge-base --is-ancestor HEAD`, because a legitimately cited commit may live on
            # another branch or a tag and must still pass.
            reach = subprocess.run(
                ["git", "merge-base", "--is-ancestor", sha, "HEAD"],
                capture_output=True, text=True, cwd=repo,
            )
            if reach.returncode != 0:
                anyref = subprocess.run(
                    ["git", "for-each-ref", "--contains", sha, "--format=%(refname)"],
                    capture_output=True, text=True, cwd=repo,
                )
                refs = [r for r in anyref.stdout.split() if r]
                if not refs:
                    return ORPHANED
                # Reachable — but from WHAT? A commit on a local-only branch is exactly as invisible
                # to everyone else as an orphan, and passes here for the same bad reason: this box
                # has a ref nobody else does. c8b65ba did precisely that — green locally, "DOES NOT
                # RESOLVE" in CI, one push after the orphan check was added to stop this very shape.
                #
                # NOT fatal, deliberately. Citing a commit in the same push that creates it is normal
                # and would fail every pre-push run, which is how a lint gets disabled. CI is the
                # enforcement — it has only the pushed refs, so it fails there if the commit never
                # left. This names them so the failure is predicted rather than discovered.
                if not any(r.startswith("refs/remotes/") or r.startswith("refs/tags/") for r in refs):
                    LOCAL_ONLY.append((sha, refs[0]))
            subj = r.stdout.strip()
            if repo != str(QUEUE.parent.parent):
                subj = f"[{pathlib.Path(repo).name}] {subj}"
            return subj
        err = r.stderr.lower()
        # "unknown revision" is a real negative. Anything else — a corrupt or unreadable ref store,
        # a permissions problem — means the search did not happen and must not read as absence.
        if "unknown revision" not in err and "bad object" not in err and "ambiguous argument" not in err:
            raise SearchError(f"{repo}: git failed while resolving {sha}: {r.stderr.strip()}")
    return None


# A path citation: an optional repo-relative directory chain ending in a Go/shell/python file and a
# line number. Deliberately not matching bare filenames — those carry no line to check against, and
# counting them as validated would be the unqualified-green shape this lint exists to avoid.
PATH_RE = re.compile(r"(?<![\w/])((?:[a-z0-9_]+/)*[a-z0-9_]+\.(?:go|sh|py)):(\d+)(?![\d])")


_MODCACHE = None


def modcache_root():
    global _MODCACHE
    if _MODCACHE is None:
        r = subprocess.run(["go", "env", "GOMODCACHE"], capture_output=True, text=True, cwd=str(ROOT))
        _MODCACHE = pathlib.Path(r.stdout.strip()) if r.returncode == 0 and r.stdout.strip() else pathlib.Path("")
    return _MODCACHE


def required_modules():
    """{module path: version} for the cross-repo modules goinfer cites, read from the ROOT go.mod.

    Derived, never restated — the same rule B7 filed against hand-maintained version literals. The
    version this returns IS the one goinfer compiles against, so a citation checked against it is a
    citation about the code goinfer actually runs.
    """
    out = {}
    # BOTH aikit modules, from the go.mod that actually requires each. aikit and aikit/gpu are
    # SEPARATE modules with separate tag series (B7, E6), so gpu/ is not inside aikit@vX's module
    # cache directory — reading only the root go.mod left every `gpu/...` citation unresolvable and
    # reddened CI on a reference that was perfectly correct.
    for mod_file, want in ((ROOT / "go.mod", "github.com/townsendmerino/aikit"),
                           (ROOT / "cuda" / "go.mod", "github.com/townsendmerino/aikit/gpu")):
        try:
            text = mod_file.read_text()
        except OSError:
            continue
        for m in re.finditer(r"^\s*(github\.com/townsendmerino/aikit(?:/gpu)?)\s+(v[0-9][^\s]*)\s*$",
                             text, re.M):
            if m.group(1) == want:
                out[m.group(1)] = m.group(2)
    return out


def modcache_dir(mod: str, ver: str):
    root = modcache_root()
    if not root or not root.exists():
        return None
    d = root / f"{mod}@{ver}"
    return d if d.is_dir() else None


def path_repos():
    """Search roots for path citations — literally the same set the commit check uses.

    These were two functions with two notions of "the sibling set", and they disagreed the moment the
    env override was exercised: the commit search honoured it and repo_present did not, so a foreign
    commit was reported fabricated while its repo was still considered present. Same defect shape as
    capSlots and its inline copy — one concept, two implementations.

    linalg/quant.go:113 and weightmat.go:202 were written as if local and are aikit paths. Resolving
    across the sibling set and RECORDING WHERE IT RESOLVED is the same repair that fixed be049df's
    false red: searching one place and reporting absence is a claim the search was not entitled to
    make.
    """
    roots = [(repo_name(r), pathlib.Path(r)) for r in sibling_repos()]
    # A cross-repo path citation resolves against the VERSION GOINFER REQUIRES, not against whatever
    # the sibling checkout happens to be on. Those are different questions and only one of them is
    # about goinfer.
    #
    # linalg/quant.go:113 went red TWICE in one day because aikit committed — the citation was fine
    # and goinfer had not changed. A gate whose verdict moves when another repository's working tree
    # moves is not measuring this repo; it is the Environment class again, with the environment being
    # somebody else's uncommitted work.
    #
    # The module cache is the right root: content-addressed and immutable per version, present in CI
    # once anything has built, reproducible on any machine, and stale EXACTLY when goinfer bumps the
    # dependency — which is when a citation into it genuinely should be re-checked.
    #
    # Placed FIRST so it wins over the sibling checkout when both exist. The sibling stays as a
    # fallback for a machine with no populated module cache.
    for mod, ver in required_modules().items():
        d = modcache_dir(mod, ver)
        if d is not None:
            roots.insert(0, (repo_name(d), d))
    return roots


def is_modcache(base) -> bool:
    r = modcache_root()
    try:
        return bool(r) and str(base).startswith(str(r))
    except Exception:
        return False


def repo_name(path) -> str:
    """The repo's NAME, from its go.mod module line — not from the directory it happens to sit in.

    A clone into a directory not called "goinfer" made path_repo_present("goinfer") false, so every
    goinfer-recorded citation was SKIPPED: 116 of them, reported as a clean green. CI checks out into
    a directory matching the repo, so it was correct there and wrong anywhere else — one more verdict
    that depended on the environment rather than on the citations.

    `module github.com/townsendmerino/goinfer` is in go.mod regardless of what the checkout is
    called, so the last element of the module path is the stable answer. Directory name remains the
    fallback for a root with no go.mod (the aikit module cache directory is `aikit@v1.17.1`, and its
    own go.mod names it, so it resolves correctly too).
    """
    p = pathlib.Path(path)
    gm = p / "go.mod"
    try:
        m = re.search(r"^module\s+(\S+)", gm.read_text(), re.M)
        if m:
            return m.group(1).rstrip("/").split("/")[-1]
    except OSError:
        pass
    name = p.name
    return name.split("@")[0]


def path_repo_present(name: str) -> bool:
    """Can PATH citations into this repo be checked here? A module-cache directory counts."""
    return any(n == name for n, _ in path_repos())


def commit_repo_present(name: str) -> bool:
    """Can COMMIT citations into this repo be checked here? Only a GIT checkout counts.

    These were one predicate, and merging them was right while both callers needed the same thing —
    a git checkout. Adding the module cache as a path root broke that premise, because a module cache
    answers "what is at line 327 of quant.go" and cannot answer "what is commit be049df": it has no
    history at all. The single predicate then reported aikit as present, the four aikit SHAs stopped
    being skipped, and CI called four accurate citations fabricated.

    That is the be049df false red for the third time, arriving by a third route, and produced BY the
    fix meant to make path resolution reproducible. The lesson is not "do not merge duplicated
    predicates" — the merge was correct. It is that a predicate answers ONE question, and adding a
    root that can answer only half of them re-split the question without re-splitting the predicate.
    """
    return any(repo_name(r) == name and (pathlib.Path(r) / ".git").exists()
               for r in sibling_repos())


# A content key only works if the content DISCRIMINATES. `//`, `}`, a blank line or a lone brace
# appear hundreds of times, so "the recorded content is now at line 114" is a coincidence rather than
# a move. Such citations are indexed as UNKEYABLE and counted, not silently mis-matched — the failure
# mode otherwise is a confident wrong answer, which is worse than no answer.
def discriminating(content: str) -> bool:
    c = content.strip()
    return len(c) >= 12 and any(ch.isalnum() for ch in c)


# When the cited line is not discriminating, key on the nearest ENCLOSING DECLARATION instead. A
# citation at a bare `//` is pointing at a line; what it MEANS is almost always a nameable thing —
# allocSlots' call site, a const, a type — and a name is discriminating by construction and survives
# reformatting inside the body. The citation then verifies "this declaration still exists" rather
# than "this line still reads the same", which is the claim the prose was making anyway.
DECL_RE = re.compile(r"^(?:func|type|const|var)\s")


def anchor_for(lines, line: int):
    for i in range(min(line, len(lines)) - 1, -1, -1):
        if DECL_RE.match(lines[i]):
            return "anchor: " + lines[i].strip()[:80]
    return None


def resolve_path(rel: str, line: int):
    """Return (repo, content) for a cited path:line, or ("", None) when the file exists nowhere.

    A file present but SHORTER than the cited line is not an error here — it is a citation whose
    content is absent, which the caller reports as such.
    """
    for name, base in path_repos():
        f = base / rel
        if f.is_file():
            RESOLVED_FROM[("module cache" if is_modcache(base) else "checkout", name)] += 1
            lines = f.read_text(errors="replace").split("\n")
            if line <= len(lines):
                c = lines[line - 1].strip()
                if discriminating(c):
                    return name, c
                a = anchor_for(lines, line)
                return name, (a if a else c)
            return name, ""
    return "", None


# A BARE file reference: same shape, no line number. Existence is checkable without a content key —
# it catches a file that moved packages or was deleted, which is most of the way to keeping a
# reference honest and costs nothing to record.
BARE_RE = re.compile(r"(?<![\w/])((?:[a-z0-9_]+/)*[a-z0-9_]+\.(?:go|sh|py))(?![\w:])")


ALLOW_RE = re.compile(r"<!--\s*sha-lint:\s*allow\s+([0-9a-f]{7,40})\s+(.+?)\s*-->")
# Path citations into a project that is not checked out here — the Go stdlib, llama.cpp's gguf-py.
# Same mechanism and same reasoning as the commit allowlist: it does not make the citation correct,
# it makes "this points outside every repo we have" explicit instead of indistinguishable from a typo.
ALLOWPATH_RE = re.compile(r"<!--\s*citation-lint:\s*allow-path\s+(\S+)\s+(.+?)\s*-->")


def path_allowlist():
    out = {}
    for doc in live_docs():
        for m in ALLOWPATH_RE.finditer(doc.read_text(errors="replace")):
            out[m.group(1)] = m.group(2)
    return out


def allowlist(text: str):
    return {m.group(1): m.group(2) for m in ALLOW_RE.finditer(text)}


def body_without_index(text: str) -> str:
    if MARK_BEGIN in text:
        return text.split(MARK_BEGIN, 1)[0]
    return text


def main() -> int:
    update = "--update" in sys.argv
    text = QUEUE.read_text()
    body = body_without_index(text)

    found = []
    for m in SHA_RE.finditer(body):
        tok = m.group(1)
        if looks_like_sha(tok) and tok not in found:
            found.append(tok)
    found.sort()

    if not found:
        # Zero citations is indistinguishable from "the regexp stopped matching". Refuse.
        sys.stderr.write("queue_sha_lint: found ZERO SHA citations — the queue always cites some, "
                         "so the extractor is broken rather than the file being clean.\n")
        return 1

    paths = []
    for doc in live_docs():
        dtxt = doc.read_text(errors="replace")
        dbody = body if doc == QUEUE else dtxt
        rel_doc = str(doc.relative_to(ROOT))
        for m in PATH_RE.finditer(dbody):
            key = f"{rel_doc}|{m.group(1)}:{m.group(2)}"
            if key not in [p[0] for p in paths]:
                paths.append((key, m.group(1), int(m.group(2))))

    bares = []
    for m in BARE_RE.finditer(body):   # bare refs: QUEUE.md only, where they carry decisions
        rel = m.group(1)
        if rel not in bares:
            bares.append(rel)
    bares.sort()

    allowed = allowlist(text)
    resolved, unresolved, orphaned = {}, [], []
    for sha in found:
        try:
            s = subject_of(sha)
        except SearchError as e:
            sys.stderr.write(f"queue_sha_lint: CANNOT SEARCH — {e}\n")
            sys.stderr.write("  This is not a missing SHA. Fix the repository path and re-run; "
                             "reporting citations as unresolved from here would be a false red.\n")
            return 2
        if s is ORPHANED:
            orphaned.append(sha)
        elif s is None:
            if sha in allowed:
                resolved[sha] = f"(unresolvable here) {allowed[sha]}"
                continue
            unresolved.append(sha)
        else:
            resolved[sha] = s

    pidx0 = {}
    if MARK_BEGIN in text:
        for line in text.split(MARK_BEGIN, 1)[1].splitlines():
            m = re.match(r"\|\s*`([^`]+:\d+)`\s*\|\s*([^|]*?)\s*\|\s*`(.*)`\s*\|$", line.strip())
            if m:
                pidx0[m.group(1)] = m.group(2)
    pallow = path_allowlist()
    presolved, pmissing = {}, []
    for key, rel, ln in paths:
        if rel in pallow or rel.split("/")[0] in pallow:
            continue
        repo, content = resolve_path(rel, ln)
        if content is None:
            if pidx0.get(key) and not path_repo_present(pidx0[key]):
                presolved[key] = (pidx0[key], None)  # foreign repo absent; skipped below
                continue
            pmissing.append((key, rel))
        else:
            presolved[key] = (repo, content)
    if pmissing:
        sys.stderr.write("queue_citation_lint: path citation(s) resolve in NO repository:\n")
        for key, rel in pmissing:
            sys.stderr.write(f"  {key}  — searched: {', '.join(n for n, _ in path_repos())}\n")
        sys.stderr.write("  A path that resolves nowhere is a hard error, not a not-found: either the\n"
                         "  citation names no real file, or it omits the repo it belongs to.\n")
        return 2

    bresolved, bmissing = {}, []
    for rel in bares:
        hit = ""
        for name, base in path_repos():
            if (base / rel).is_file():
                hit = name
                break
        if hit:
            bresolved[rel] = hit
        else:
            bmissing.append(rel)

    if update:
        lines = [MARK_BEGIN, "", "## SHA index", "",
                 "Generated. Every commit id cited above, with the subject it resolved to at the time",
                 "of generation. Regenerate with `scripts/queue_sha_lint.py --update`.", "",
                 "| sha | subject |", "|---|---|"]
        for sha in sorted(resolved):
            if sha in allowed:
                continue
            lines.append(f"| `{sha}` | {resolved[sha].replace('|', '\\|')} |")
        for sha in unresolved:
            lines.append(f"| `{sha}` | **UNRESOLVED** |")
        lines += ["", "## Path index", "",
                  "Generated. Every `file:line` cited above, the repo it resolved in, and the trimmed",
                  "content of that line. A line that MOVED is reported with its new number; content that",
                  "has VANISHED is red, because the citation then claims something the file no longer",
                  "supports.", "",
                  "| doc \\| path:line | repo | line content |", "|---|---|---|"]
        for key in sorted(presolved):
            repo, content = presolved[key]
            if content is None:
                continue
            keyable = discriminating(content) or content.startswith("anchor: ")
            body_txt = content.replace('|', chr(92) + '|')[:88] if keyable else "UNKEYABLE"
            lines.append(f"| `{key}` | {repo} | `{body_txt}` |")
        lines += ["", "## Bare file index", "",
                  "Generated. Every file referenced WITHOUT a line number, and the repo it resolves in.",
                  "Existence only — there is no line to key content against, which is recorded rather",
                  "than papered over.", "",
                  "| file | repo |", "|---|---|"]
        for rel in sorted(bresolved):
            lines.append(f"| `{rel}` | {bresolved[rel]} |")
        for rel in bmissing:
            lines.append(f"| `{rel}` | **RESOLVES NOWHERE** |")
        lines += ["", MARK_END, ""]
        QUEUE.write_text(body.rstrip("\n") + "\n\n" + "\n".join(lines))
        print(f"queue_sha_lint: indexed {len(resolved)} SHAs ({len(unresolved)} unresolved)")
        return 1 if unresolved else 0

    if MARK_END not in text:
        sys.stderr.write("queue_sha_lint: no SHA index in docs/QUEUE.md — run with --update\n")
        return 1

    index = {}
    for line in text.split(MARK_BEGIN, 1)[1].splitlines():
        m = re.match(r"\|\s*`([0-9a-f]{7,40})`\s*\|\s*(.*?)\s*\|$", line.strip())
        if m:
            index[m.group(1)] = m.group(2)

    bad = []
    unkeyable = []
    skipped_foreign = []
    for sha in unresolved:
        # The index records a foreign subject as "[repo] subject". If that repo is not checked out
        # here — CI clones goinfer alone — the citation is UNCHECKED, not fabricated. Reporting it as
        # fabricated is the be049df false red, reintroduced by a different route.
        rec = index.get(sha, "")
        m = re.match(r"\[([a-z0-9_-]+)\]", rec)
        if m and not commit_repo_present(m.group(1)):
            skipped_foreign.append((sha, m.group(1)))
            continue
        bad.append(f"  {sha}  DOES NOT RESOLVE — fabricated, mistyped, or from a dropped branch")
    for sha in orphaned:
        bad.append(f"  {sha}  ORPHANED — it resolves in this local object store but is reachable "
                   f"from NO ref.\n      An amended, rebased or deleted-branch commit. It survives "
                   f"here in the reflog until gc, and is a hard failure in any fresh clone, so a "
                   f"green on this machine would not travel.\n      Re-point the citation at the "
                   f"commit that replaced it.")
    for sha, subj in resolved.items():
        if sha in allowed:
            continue  # declared unresolvable, with a stated reason; nothing to compare against
        rec = index.get(sha)
        if rec is None:
            bad.append(f"  {sha}  cited but absent from the index — run --update")
        elif rec.replace("\\|", "|") != subj:
            bad.append(f"  {sha}  subject changed\n      indexed: {rec}\n      actual:  {subj}")
    for sha in index:
        if sha not in resolved and sha not in unresolved and sha not in allowed:
            bad.append(f"  {sha}  indexed but no longer cited — run --update")

    pindex = {}
    for line in text.split(MARK_BEGIN, 1)[1].splitlines():
        m = re.match(r"\|\s*`([^`]+:\d+)`\s*\|\s*([^|]*?)\s*\|\s*`(.*)`\s*\|$", line.strip())
        if m:
            pindex[m.group(1)] = (m.group(2), m.group(3))
    for key, rel, ln in paths:
        if rel in pallow or rel.split("/")[0] in pallow:
            continue
        rec0 = pindex.get(key)
        if rec0 is not None and rec0[0] and not path_repo_present(rec0[0]):
            # The index records which repo this resolved in. If that repo is not checked out here —
            # CI clones goinfer alone — the citation is UNCHECKED, not broken. Counted and named, so
            # a skip and a pass do not look the same.
            skipped_foreign.append((key, rec0[0]))
            continue
        repo, content = presolved[key]
        rec = rec0
        if rec is None:
            bad.append(f"  {key}  cited but absent from the path index — run --update")
            continue
        want = rec[1].replace(chr(92) + "|", "|")
        if want == "UNKEYABLE" or not (discriminating(content) or content.startswith("anchor: ")):
            unkeyable.append(key)
            continue
        if content[:88] == want:
            continue
        if want.startswith("anchor: "):
            # The anchor is a declaration; look for it anywhere in the file before calling it gone.
            decl = want[len("anchor: "):]
            for _n, _b in path_repos():
                _f = _b / rel
                if _f.is_file() and any(l.strip()[:80] == decl for l in _f.read_text(errors="replace").split("\n")):
                    break
            else:
                bad.append(f"  {key}  ANCHOR GONE — the citation pointed at `{decl[:52]}`, which is "
                           f"no longer in the file")
            continue
        # The content moved or vanished. Look for it elsewhere in the file before calling it red.
        found_at = None
        for name, base in path_repos():
            f = base / rel
            if f.is_file():
                for i, l in enumerate(f.read_text(errors="replace").split("\n"), 1):
                    if l.strip()[:88] == want and want:
                        found_at = i
                        break
            if found_at:
                break
        if found_at:
            bad.append(f"  {key}  SHIFTED — the cited content is now at line {found_at}. "
                       f"Update the citation to {rel}:{found_at} and re-run --update.")
        else:
            bad.append(f"  {key}  CONTENT ABSENT — the line now reads {content[:60]!r}, and the "
                       f"recorded content {want[:60]!r} is nowhere in the file. The citation claims "
                       f"something the file no longer supports.")

    bindex = {}
    for line in text.split(MARK_BEGIN, 1)[1].splitlines():
        m = re.match(r"\|\s*`([^`]+\.(?:go|sh|py))`\s*\|\s*([^|]*?)\s*\|$", line.strip())
        if m:
            bindex[m.group(1)] = m.group(2)
    still = []
    for rel in bmissing:
        rec = bindex.get(rel, "")
        if rec and rec != "**RESOLVES NOWHERE**" and not path_repo_present(rec):
            skipped_foreign.append((rel, rec))
            continue
        still.append(rel)
    for rel in still:
        bad.append(f"  {rel}  bare reference resolves in NO repository "
                   f"({', '.join(n for n, _ in path_repos())}) — moved package, deleted, or a typo")

    if bad:
        sys.stderr.write("queue_citation_lint: docs/QUEUE.md citations are not sound:\n")
        sys.stderr.write("\n".join(bad) + "\n")
        return 1
    if allowed:
        print(f"queue_sha_lint: {len(allowed)} citation(s) DECLARED unresolvable here:")
        for sha, why in sorted(allowed.items()):
            print(f"    {sha}  {why}")
    if unkeyable:
        print(f"queue_citation_lint: {len(unkeyable)} citation(s) UNKEYABLE — the cited line's content "
              f"does not discriminate (a bare `//`, a brace, a blank), so a match would be coincidence:")
        for k in sorted(unkeyable):
            print(f"    {k}")
    if skipped_foreign:
        print(f"queue_citation_lint: SKIPPED {len(skipped_foreign)} citation(s) — the repo they "
              f"resolved in is not checked out here:")
        for k, r in sorted(skipped_foreign):
            print(f"    {k}  (recorded in: {r})")
    ndocs = len({k.split("|", 1)[0] for k, _, _ in paths})
    # DENOMINATOR, stated every run alongside the numerator. "VALIDATED N" alone cannot distinguish
    # a clean tree from a scanner whose universe shrank — an rglob that stops matching, or a doc that
    # moved under an excluded prefix, both report a smaller green N.
    _all_md = [f for f in ROOT.rglob("*.md") if "/.git/" not in str(f)]
    _buried = [f for f in _all_md if "docs/completed/" in str(f)]
    _internal = [f for f in _all_md if "docs/internal/" in str(f)]
    print(f"queue_citation_lint: EXAMINED {len(live_docs())} live markdown document(s) of "
          f"{len(_all_md)} in the tree ({len(_buried)} excluded as docs/completed/ by the archival "
          f"rule below; {len(_internal)} excluded as docs/internal/, which is gitignored and so "
          f"resolves on this machine only). A document that leaves this denominator leaves the "
          f"lint silently.")
    print(f"queue_citation_lint: VALIDATED {len(resolved) - len(allowed)} commit citation(s), "
          f"{len(paths) - len(unkeyable)} path:line citation(s) across {ndocs} live document(s), and "
          f"{len(bresolved)} bare file reference(s) in the queue (existence only).")
    if unkeyable:
        print(f"  {len(unkeyable)} path citation(s) are EXISTENCE-CHECKED ONLY — their line content "
              f"does not discriminate, so a shift in them is invisible.")
    if LOCAL_ONLY:
        print(f"  {len(LOCAL_ONLY)} citation(s) resolve here ONLY VIA A LOCAL REF — they will fail in CI "
              f"until pushed, because CI has only the published refs:")
        for sha, ref in sorted(set(LOCAL_ONLY)):
            print(f"    {sha}  reachable from {ref} — push it, or allowlist it with a reason")
        print("    Not failed here on purpose: citing a commit in the same push that creates it is "
              "normal. CI is the enforcement; this is the advance warning.")
    # THE VERSION-PINNED RESOLUTION, reported rather than assumed. A required module whose cache is
    # cold AND which has no sibling checkout cannot be searched at all — and by the could-not-search
    # rule that is a HARD ERROR, never a skip: reporting "unchecked" when the answer is "we could not
    # look" is how a green comes to cover nothing. CI populates the cache with `go build ./...`
    # before this step; if that ever stops being true, this says so instead of quietly narrowing.
    cold_modules = []
    nmc = sum(c for (k, _), c in RESOLVED_FROM.items() if k == "module cache")
    nco = sum(c for (k, _), c in RESOLVED_FROM.items() if k == "checkout")
    print(f"  CROSS-REPO RESOLUTION: {nmc} path lookup(s) answered from the MODULE CACHE at the "
          f"version go.mod requires, {nco} from a checkout.")
    for mod, ver in sorted(required_modules().items()):
        name = mod.rstrip("/").split("/")[-1]
        cached = modcache_dir(mod, ver) is not None
        sib = commit_repo_present(name)
        state = ("module cache @ " + ver) if cached else ("sibling checkout" if sib else "NOWHERE")
        print(f"    {mod} -> {state}")
        if not cached and not sib:
            print(f"      COLD CACHE and no checkout — citations into {name} could not be searched. "
                  f"Run `go mod download` before this lint; a skip here would be a green that "
                  f"covers nothing.")
            cold_modules.append(mod)
    if nmc == 0 and required_modules():
        print("    NOTE: zero lookups used the module cache. Either no citation points into a "
              "required module, or the pinning is not being exercised here — the second is the "
              "exercised-but-never-triggered shape and worth checking.")
    print("  docs/completed/ is EXCLUDED on purpose — archived records are supposed to age with the "
          "code they described, and linting them would fight the archival rule.")
    print("  NOT validated: RELEVANCE. A commit citation is checked to resolve and to match its "
          "recorded subject; nothing checks that the commit SUPPORTS the claim made about it.")
    print("    9e5f8fa passed green through two documents for weeks as \"the goldens-refresh "
          "precedent\" while touching the manifest not at all — a resolving sha with a matching "
          "subject and a false claim attached.")
    print("    The same gap on the PATH side, and worse because the anchor keeps working: "
          "docs/task-moe-streaming.md read \"goinfer is now on aikit v1.16.0 (go.mod:6)\". The "
          "aikit bump changed what go.mod:6 SAYS without changing that it is the aikit require, so "
          "the content key still matched and the citation stayed green while the version it "
          "asserted went stale. A path citation is checked to point somewhere stable — not to "
          "still mean what the sentence around it claims.")
    print("  Also NOT validated: every test name, tag, env var and URL — and for the bare file "
          "references, WHAT IS SAID ABOUT THEM, since there is no line to key against.")
    print("  A lint on a document raises trust in EVERY citation in it, not only the kinds it checks — "
          "so the scope is printed with the green.")
    if cold_modules:
        sys.stderr.write("queue_citation_lint: CANNOT SEARCH — no module cache and no checkout for: "
                         + ", ".join(cold_modules) + "\n")
        sys.stderr.write("  This is a hard failure on purpose. Citations into these modules were not "
                         "checked, and calling that a skip would make the green cover nothing.\n")
        sys.stderr.write("  Fix: run `go mod download` (CI does `go build ./...`) before this lint.\n")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
