#!/usr/bin/env python3
"""queue_sha_lint.py — every SHA cited in docs/QUEUE.md must resolve, and its subject must match.

WHY THIS EXISTS. `9e5f8fa` was cited in docs/QUEUE.md as the precedent for a goldens-gated deps_hash
refresh — "a metadata field addition re-staled weights.go and the refresh ran 19 goldens". It is
`fix(quant): reject --quant that conflicts with a prequant .giw at startup` and touches the manifest
not at all. The wrong SHA was then repeated several times, from the file, without anyone opening it.

That is what a state document is *for*, and why an error in one is worse than the same error in
conversation: nothing re-derives what a state document asserts. A claim made in passing gets
re-checked when it matters; a claim written into the queue gets cited. So the error propagated with
more confidence than it started with.

The remedy is mechanical. This lint extracts every SHA-looking token from the queue, resolves it, and
compares its subject against a recorded index at the bottom of the file. `--update` regenerates the
index. Two failure modes are covered, and both were mutation-checked:

  - a SHA that does not resolve  -> fabricated, mistyped, or from a dropped branch
  - a SHA whose subject changed  -> the index is stale, or the citation was always wrong

A citation that cannot resolve here but is still legitimate — another repository, a commit that
never left a machine — is declared explicitly:

    <!-- sha-lint: allow <sha> <reason> -->

The reason is mandatory and is printed by the lint. That is the whole mechanism: it does not make
the citation correct, it makes the fact that nobody has verified it VISIBLE, which is the state
9e5f8fa was in for weeks while reading as authoritative.

Deliberately NOT checking that the surrounding prose describes the commit accurately — that is not
mechanisable. It checks the citation, which is the part that was wrong.
"""

import os
import pathlib
import re
import subprocess
import sys

QUEUE = pathlib.Path(__file__).resolve().parent.parent / "docs" / "QUEUE.md"
MARK_BEGIN = "<!-- SHA-INDEX: generated by scripts/queue_sha_lint.py --update; do not edit by hand -->"
MARK_END = "<!-- /SHA-INDEX -->"

# 7-40 hex chars delimited by non-word characters. Requires at least one digit AND one letter, which
# is what separates a commit id from an English word like "deffff" or a decimal figure like 1234567.
SHA_RE = re.compile(r"(?<![0-9a-zA-Z_])([0-9a-f]{7,40})(?![0-9a-zA-Z_])")


def looks_like_sha(tok: str) -> bool:
    return any(c.isdigit() for c in tok) and any(c.isalpha() for c in tok)


# The queue legitimately cites SIBLING repositories — aikit's gpu module ships the kernels goinfer
# embeds, so its SHAs appear here as a matter of course. Searching only this repo made a correct
# citation (be049df) look fabricated, which is a false RED and exactly as bad as the false green the
# lint exists to prevent: it would have driven someone to "fix" an accurate reference.
#
# Override with GOINFER_SHA_LINT_REPOS (colon-separated). Absent repos are skipped silently — they
# are a property of the machine, not of the queue.
def sibling_repos():
    root = QUEUE.parent.parent
    env = os.environ.get("GOINFER_SHA_LINT_REPOS")
    cands = env.split(":") if env else [str(root / ".." / "aikit" / "aikit")]
    out = [str(root)]
    for c in cands:
        pp = pathlib.Path(c).expanduser()
        if (pp / ".git").exists():
            out.append(str(pp))
    return out


def subject_of(sha: str):
    for repo in sibling_repos():
        r = subprocess.run(
            ["git", "log", "-1", "--format=%s", sha],
            capture_output=True, text=True, cwd=repo,
        )
        if r.returncode == 0:
            subj = r.stdout.strip()
            if repo != str(QUEUE.parent.parent):
                subj = f"[{pathlib.Path(repo).name}] {subj}"
            return subj
    return None


ALLOW_RE = re.compile(r"<!--\s*sha-lint:\s*allow\s+([0-9a-f]{7,40})\s+(.+?)\s*-->")


def allowlist(text: str):
    return {m.group(1): m.group(2) for m in ALLOW_RE.finditer(text)}


def body_without_index(text: str) -> str:
    if MARK_BEGIN in text:
        return text.split(MARK_BEGIN, 1)[0]
    return text


def main() -> int:
    update = "--update" in sys.argv
    text = QUEUE.read_text()
    body = body_without_index(text)

    found = []
    for m in SHA_RE.finditer(body):
        tok = m.group(1)
        if looks_like_sha(tok) and tok not in found:
            found.append(tok)
    found.sort()

    if not found:
        # Zero citations is indistinguishable from "the regexp stopped matching". Refuse.
        sys.stderr.write("queue_sha_lint: found ZERO SHA citations — the queue always cites some, "
                         "so the extractor is broken rather than the file being clean.\n")
        return 1

    allowed = allowlist(text)
    resolved, unresolved = {}, []
    for sha in found:
        s = subject_of(sha)
        if s is None:
            if sha in allowed:
                resolved[sha] = f"(unresolvable here) {allowed[sha]}"
                continue
            unresolved.append(sha)
        else:
            resolved[sha] = s

    if update:
        lines = [MARK_BEGIN, "", "## SHA index", "",
                 "Generated. Every commit id cited above, with the subject it resolved to at the time",
                 "of generation. Regenerate with `scripts/queue_sha_lint.py --update`.", "",
                 "| sha | subject |", "|---|---|"]
        for sha in sorted(resolved):
            if sha in allowed:
                continue
            lines.append(f"| `{sha}` | {resolved[sha].replace('|', '\\|')} |")
        for sha in unresolved:
            lines.append(f"| `{sha}` | **UNRESOLVED** |")
        lines += ["", MARK_END, ""]
        QUEUE.write_text(body.rstrip("\n") + "\n\n" + "\n".join(lines))
        print(f"queue_sha_lint: indexed {len(resolved)} SHAs ({len(unresolved)} unresolved)")
        return 1 if unresolved else 0

    if MARK_END not in text:
        sys.stderr.write("queue_sha_lint: no SHA index in docs/QUEUE.md — run with --update\n")
        return 1

    index = {}
    for line in text.split(MARK_BEGIN, 1)[1].splitlines():
        m = re.match(r"\|\s*`([0-9a-f]{7,40})`\s*\|\s*(.*?)\s*\|$", line.strip())
        if m:
            index[m.group(1)] = m.group(2)

    bad = []
    for sha in unresolved:
        bad.append(f"  {sha}  DOES NOT RESOLVE — fabricated, mistyped, or from a dropped branch")
    for sha, subj in resolved.items():
        if sha in allowed:
            continue  # declared unresolvable, with a stated reason; nothing to compare against
        rec = index.get(sha)
        if rec is None:
            bad.append(f"  {sha}  cited but absent from the index — run --update")
        elif rec.replace("\\|", "|") != subj:
            bad.append(f"  {sha}  subject changed\n      indexed: {rec}\n      actual:  {subj}")
    for sha in index:
        if sha not in resolved and sha not in unresolved and sha not in allowed:
            bad.append(f"  {sha}  indexed but no longer cited — run --update")

    if bad:
        sys.stderr.write("queue_sha_lint: docs/QUEUE.md SHA citations are not sound:\n")
        sys.stderr.write("\n".join(bad) + "\n")
        return 1
    if allowed:
        print(f"queue_sha_lint: {len(allowed)} citation(s) DECLARED unresolvable here:")
        for sha, why in sorted(allowed.items()):
            print(f"    {sha}  {why}")
    print(f"queue_sha_lint: {len(resolved) - len(allowed)} SHA citations resolve and match their recorded subjects")
    return 0


if __name__ == "__main__":
    sys.exit(main())
