#!/usr/bin/env python3
"""queue_citation_lint.py — every citation in docs/QUEUE.md must resolve, and its target must match.

Two kinds are checked: COMMIT citations (sha -> subject) and PATH citations (file:line -> the trimmed
content of that line). Both are recorded in a generated index at the bottom of the file and compared
on every run.

WHY THIS EXISTS. `9e5f8fa` was cited in docs/QUEUE.md as the precedent for a goldens-gated deps_hash
refresh — "a metadata field addition re-staled weights.go and the refresh ran 19 goldens". It is
`fix(quant): reject --quant that conflicts with a prequant .giw at startup` and touches the manifest
not at all. The wrong SHA was then repeated several times, from the file, without anyone opening it.

That is what a state document is *for*, and why an error in one is worse than the same error in
conversation: nothing re-derives what a state document asserts. A claim made in passing gets
re-checked when it matters; a claim written into the queue gets cited. So the error propagated with
more confidence than it started with.

The remedy is mechanical. This lint extracts every SHA-looking token from the queue, resolves it, and
compares its subject against a recorded index at the bottom of the file. `--update` regenerates the
index. Two failure modes are covered, and both were mutation-checked:

  - a SHA that does not resolve  -> fabricated, mistyped, or from a dropped branch
  - a SHA whose subject changed  -> the index is stale, or the citation was always wrong

A citation that cannot resolve here but is still legitimate — another repository, a commit that
never left a machine — is declared explicitly:

    <!-- sha-lint: allow <sha> <reason> -->

The reason is mandatory and is printed by the lint. That is the whole mechanism: it does not make
the citation correct, it makes the fact that nobody has verified it VISIBLE, which is the state
9e5f8fa was in for weeks while reading as authoritative.

Deliberately NOT checking that the surrounding prose describes the commit accurately — that is not
mechanisable. It checks the citation, which is the part that was wrong.
"""

import os
import pathlib
import re
import subprocess
import sys

QUEUE = pathlib.Path(__file__).resolve().parent.parent / "docs" / "QUEUE.md"
MARK_BEGIN = "<!-- CITATION-INDEX: generated by scripts/queue_citation_lint.py --update; do not edit by hand -->"
MARK_END = "<!-- /CITATION-INDEX -->"

# 7-40 hex chars delimited by non-word characters. Requires at least one digit AND one letter, which
# is what separates a commit id from an English word like "deffff" or a decimal figure like 1234567.
SHA_RE = re.compile(r"(?<![0-9a-zA-Z_])([0-9a-f]{7,40})(?![0-9a-zA-Z_])")


def looks_like_sha(tok: str) -> bool:
    return any(c.isdigit() for c in tok) and any(c.isalpha() for c in tok)


# The queue legitimately cites SIBLING repositories — aikit's gpu module ships the kernels goinfer
# embeds, so its SHAs appear here as a matter of course. Searching only this repo made a correct
# citation (be049df) look fabricated, which is a false RED and exactly as bad as the false green the
# lint exists to prevent: it would have driven someone to "fix" an accurate reference.
#
# Override with GOINFER_SHA_LINT_REPOS (colon-separated). Absent repos are skipped silently — they
# are a property of the machine, not of the queue.
class SearchError(Exception):
    """A repository could not be searched — distinct from a SHA not being found in it."""


def sibling_repos():
    root = QUEUE.parent.parent
    env = os.environ.get("GOINFER_SHA_LINT_REPOS")
    if env:
        # EXPLICITLY named repos are required to be searchable. A typo'd or moved path must be a hard
        # error, not a silent narrowing of the search — that is precisely how be049df, a correct
        # citation contained in six released tags, was reported as fabricated: the aikit path was one
        # level off, `git -C` failed for that reason, and the failure was read as absence.
        out = [str(root)]
        for c in env.split(":"):
            pp = pathlib.Path(c).expanduser()
            if not (pp / ".git").exists():
                raise SearchError(f"GOINFER_SHA_LINT_REPOS names {pp}, which is not a git repository")
            out.append(str(pp))
        return out
    # The DEFAULT sibling is best-effort: its absence is a property of the machine, not of the queue.
    out = [str(root)]
    dflt = (root / ".." / "aikit" / "aikit").resolve()
    if (dflt / ".git").exists():
        out.append(str(dflt))
    return out


def subject_of(sha: str):
    """Return the subject, or None if the SHA is genuinely absent from every searchable repo.

    Raises SearchError if a repo could not be searched at all. "Could not look" and "looked and did
    not find" are different answers, and conflating them produces a false RED on a correct citation —
    which costs more than a false green, because it prompts someone to change something accurate.
    """
    for repo in sibling_repos():
        probe = subprocess.run(["git", "rev-parse", "--git-dir"],
                               capture_output=True, text=True, cwd=repo)
        if probe.returncode != 0:
            raise SearchError(f"{repo}: not a usable git repository ({probe.stderr.strip()})")
        r = subprocess.run(
            ["git", "log", "-1", "--format=%s", sha],
            capture_output=True, text=True, cwd=repo,
        )
        if r.returncode == 0:
            subj = r.stdout.strip()
            if repo != str(QUEUE.parent.parent):
                subj = f"[{pathlib.Path(repo).name}] {subj}"
            return subj
        err = r.stderr.lower()
        # "unknown revision" is a real negative. Anything else — a corrupt or unreadable ref store,
        # a permissions problem — means the search did not happen and must not read as absence.
        if "unknown revision" not in err and "bad object" not in err and "ambiguous argument" not in err:
            raise SearchError(f"{repo}: git failed while resolving {sha}: {r.stderr.strip()}")
    return None


# A path citation: an optional repo-relative directory chain ending in a Go/shell/python file and a
# line number. Deliberately not matching bare filenames — those carry no line to check against, and
# counting them as validated would be the unqualified-green shape this lint exists to avoid.
PATH_RE = re.compile(r"(?<![\w/])((?:[a-z0-9_]+/)*[a-z0-9_]+\.(?:go|sh|py)):(\d+)(?![\d])")


def path_repos():
    """Search roots for path citations — the same sibling set the commit check uses.

    linalg/quant.go:113 and weightmat.go:202 were written as if local and are aikit paths. Resolving
    across the sibling set and RECORDING WHERE IT RESOLVED is the same repair that fixed be049df's
    false red: searching one place and reporting absence is a claim the search was not entitled to
    make.
    """
    root = QUEUE.parent.parent
    out = [(root.name, root)]
    dflt = (root / ".." / "aikit" / "aikit").resolve()
    if (dflt / ".git").exists():
        out.append((dflt.name, dflt))
    return out


def resolve_path(rel: str, line: int):
    """Return (repo, content) for a cited path:line, or ("", None) when the file exists nowhere.

    A file present but SHORTER than the cited line is not an error here — it is a citation whose
    content is absent, which the caller reports as such.
    """
    for name, base in path_repos():
        f = base / rel
        if f.is_file():
            lines = f.read_text(errors="replace").split("\n")
            if line <= len(lines):
                return name, lines[line - 1].strip()
            return name, ""
    return "", None


ALLOW_RE = re.compile(r"<!--\s*sha-lint:\s*allow\s+([0-9a-f]{7,40})\s+(.+?)\s*-->")


def allowlist(text: str):
    return {m.group(1): m.group(2) for m in ALLOW_RE.finditer(text)}


def body_without_index(text: str) -> str:
    if MARK_BEGIN in text:
        return text.split(MARK_BEGIN, 1)[0]
    return text


def main() -> int:
    update = "--update" in sys.argv
    text = QUEUE.read_text()
    body = body_without_index(text)

    found = []
    for m in SHA_RE.finditer(body):
        tok = m.group(1)
        if looks_like_sha(tok) and tok not in found:
            found.append(tok)
    found.sort()

    if not found:
        # Zero citations is indistinguishable from "the regexp stopped matching". Refuse.
        sys.stderr.write("queue_sha_lint: found ZERO SHA citations — the queue always cites some, "
                         "so the extractor is broken rather than the file being clean.\n")
        return 1

    paths = []
    for m in PATH_RE.finditer(body):
        key = f"{m.group(1)}:{m.group(2)}"
        if key not in [p[0] for p in paths]:
            paths.append((key, m.group(1), int(m.group(2))))

    allowed = allowlist(text)
    resolved, unresolved = {}, []
    for sha in found:
        try:
            s = subject_of(sha)
        except SearchError as e:
            sys.stderr.write(f"queue_sha_lint: CANNOT SEARCH — {e}\n")
            sys.stderr.write("  This is not a missing SHA. Fix the repository path and re-run; "
                             "reporting citations as unresolved from here would be a false red.\n")
            return 2
        if s is None:
            if sha in allowed:
                resolved[sha] = f"(unresolvable here) {allowed[sha]}"
                continue
            unresolved.append(sha)
        else:
            resolved[sha] = s

    presolved, pmissing = {}, []
    for key, rel, ln in paths:
        repo, content = resolve_path(rel, ln)
        if content is None:
            pmissing.append((key, rel))
        else:
            presolved[key] = (repo, content)
    if pmissing:
        sys.stderr.write("queue_citation_lint: path citation(s) resolve in NO repository:\n")
        for key, rel in pmissing:
            sys.stderr.write(f"  {key}  — searched: {', '.join(n for n, _ in path_repos())}\n")
        sys.stderr.write("  A path that resolves nowhere is a hard error, not a not-found: either the\n"
                         "  citation names no real file, or it omits the repo it belongs to.\n")
        return 2

    if update:
        lines = [MARK_BEGIN, "", "## SHA index", "",
                 "Generated. Every commit id cited above, with the subject it resolved to at the time",
                 "of generation. Regenerate with `scripts/queue_sha_lint.py --update`.", "",
                 "| sha | subject |", "|---|---|"]
        for sha in sorted(resolved):
            if sha in allowed:
                continue
            lines.append(f"| `{sha}` | {resolved[sha].replace('|', '\\|')} |")
        for sha in unresolved:
            lines.append(f"| `{sha}` | **UNRESOLVED** |")
        lines += ["", "## Path index", "",
                  "Generated. Every `file:line` cited above, the repo it resolved in, and the trimmed",
                  "content of that line. A line that MOVED is reported with its new number; content that",
                  "has VANISHED is red, because the citation then claims something the file no longer",
                  "supports.", "",
                  "| path:line | repo | line content |", "|---|---|---|"]
        for key in sorted(presolved):
            repo, content = presolved[key]
            lines.append(f"| `{key}` | {repo} | `{content.replace('|', chr(92) + '|')[:88]}` |")
        lines += ["", MARK_END, ""]
        QUEUE.write_text(body.rstrip("\n") + "\n\n" + "\n".join(lines))
        print(f"queue_sha_lint: indexed {len(resolved)} SHAs ({len(unresolved)} unresolved)")
        return 1 if unresolved else 0

    if MARK_END not in text:
        sys.stderr.write("queue_sha_lint: no SHA index in docs/QUEUE.md — run with --update\n")
        return 1

    index = {}
    for line in text.split(MARK_BEGIN, 1)[1].splitlines():
        m = re.match(r"\|\s*`([0-9a-f]{7,40})`\s*\|\s*(.*?)\s*\|$", line.strip())
        if m:
            index[m.group(1)] = m.group(2)

    bad = []
    for sha in unresolved:
        bad.append(f"  {sha}  DOES NOT RESOLVE — fabricated, mistyped, or from a dropped branch")
    for sha, subj in resolved.items():
        if sha in allowed:
            continue  # declared unresolvable, with a stated reason; nothing to compare against
        rec = index.get(sha)
        if rec is None:
            bad.append(f"  {sha}  cited but absent from the index — run --update")
        elif rec.replace("\\|", "|") != subj:
            bad.append(f"  {sha}  subject changed\n      indexed: {rec}\n      actual:  {subj}")
    for sha in index:
        if sha not in resolved and sha not in unresolved and sha not in allowed:
            bad.append(f"  {sha}  indexed but no longer cited — run --update")

    pindex = {}
    for line in text.split(MARK_BEGIN, 1)[1].splitlines():
        m = re.match(r"\|\s*`([^`]+:\d+)`\s*\|\s*([^|]*?)\s*\|\s*`(.*)`\s*\|$", line.strip())
        if m:
            pindex[m.group(1)] = (m.group(2), m.group(3))
    for key, rel, ln in paths:
        repo, content = presolved[key]
        rec = pindex.get(key)
        if rec is None:
            bad.append(f"  {key}  cited but absent from the path index — run --update")
            continue
        want = rec[1].replace(chr(92) + "|", "|")
        if content[:88] == want:
            continue
        # The content moved or vanished. Look for it elsewhere in the file before calling it red.
        found_at = None
        for name, base in path_repos():
            f = base / rel
            if f.is_file():
                for i, l in enumerate(f.read_text(errors="replace").split("\n"), 1):
                    if l.strip()[:88] == want and want:
                        found_at = i
                        break
            if found_at:
                break
        if found_at:
            bad.append(f"  {key}  SHIFTED — the cited content is now at line {found_at}. "
                       f"Update the citation to {rel}:{found_at} and re-run --update.")
        else:
            bad.append(f"  {key}  CONTENT ABSENT — the line now reads {content[:60]!r}, and the "
                       f"recorded content {want[:60]!r} is nowhere in the file. The citation claims "
                       f"something the file no longer supports.")

    if bad:
        sys.stderr.write("queue_citation_lint: docs/QUEUE.md citations are not sound:\n")
        sys.stderr.write("\n".join(bad) + "\n")
        return 1
    if allowed:
        print(f"queue_sha_lint: {len(allowed)} citation(s) DECLARED unresolvable here:")
        for sha, why in sorted(allowed.items()):
            print(f"    {sha}  {why}")
    bare = len(re.findall(r"(?<![\w/])(?:[a-z0-9_]+/)*[a-z0-9_]+\.(?:go|sh|py)(?![\w:])", body))
    print(f"queue_citation_lint: VALIDATED {len(resolved) - len(allowed)} commit citation(s) "
          f"and {len(paths)} path:line citation(s).")
    print(f"  NOT validated: {bare} bare file reference(s) with no line number, plus every test name, "
          f"tag, env var, URL and prose claim in the file.")
    print("  A lint on a document raises trust in EVERY citation in it, not only the kinds it checks — "
          "so the scope is printed with the green.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
